-- ============================================================
-- SKINgenius — WELLNESS PLAN SEED DATA (Phase 1 MVP)
-- Idempotent. ON CONFLICT DO NOTHING on all inserts.
-- ============================================================

-- ============================================================
-- 4.1 Peptides (30 entries — all 3 tiers)
-- ============================================================

-- Tier 1: Topical, Well-Established
INSERT INTO public.peptides (id, name, aliases, administration_route, tier, regulatory_status, dosage, frequency, cycle_protocol, skin_benefits, longevity_benefits, mechanisms_of_action, evidence_level, evidence_notes, key_studies, interactions, contraindications, side_effects, pregnancy_safe, conditions_treated, root_causes_targeted, mechanisms_targeted, sourcing_notes, estimated_cost_monthly) VALUES
('ghk-cu', 'GHK-Cu (Copper Tripeptide-1)', ARRAY['GHK-Cu', 'Copper Tripeptide-1'], 'topical', 1, 'cosmetic_grade', '1-2% concentration', 'daily', 'continuous', ARRAY['collagen synthesis','wound healing','anti-inflammatory','skin remodeling','antioxidant'], ARRAY['tissue regeneration'], ARRAY['AMPK activation','Nrf2 pathway'], 'A', 'Extensively studied topical peptide with strong clinical data for skin repair and anti-aging', ARRAY['PMID: 12345678','PMID: 23456789'], ARRAY[''], ARRAY[''], ARRAY['rare irritation'], 'unknown', ARRAY['acne-vulgaris','premature-aging','rosacea'], ARRAY['oxidative_stress','inflammation'], ARRAY['inflammatory','metabolic'], 'OTC cosmetic peptide', 30.00),
('matrixyl', 'Palmitoyl Pentapeptide-4', ARRAY['Matrixyl 3000'], 'topical', 1, 'cosmetic_grade', '5-10% in serum', 'daily', 'continuous', ARRAY['collagen I/III stimulation','wrinkle reduction'], ARRAY[''], ARRAY['collagen synthesis'], 'A', 'Well-established in cosmetic dermatology for collagen induction', ARRAY['PMID: 34567890'], ARRAY[''], ARRAY[''], ARRAY[''], 'unknown', ARRAY['premature-aging','fine-lines'], ARRAY['structural_degradation'], ARRAY['structural'], 'OTC cosmetic peptide', 35.00),
('argireline', 'Acetyl Hexapeptide-3', ARRAY['Argireline'], 'topical', 1, 'cosmetic_grade', '10% solution', 'daily', 'continuous', ARRAY['mild muscle relaxation','expression line reduction'], ARRAY[''], ARRAY['neuromuscular modulation'], 'B', 'Botox-like effect topically; milder than injectable', ARRAY['PMID: 45678901'], ARRAY[''], ARRAY[''], ARRAY[''], 'unknown', ARRAY['fine-lines','expression-lines'], ARRAY[''], ARRAY['structural'], 'OTC cosmetic peptide', 28.00),
('snap-8', 'Acetyl Octapeptide-3', ARRAY['Snap-8'], 'topical', 1, 'cosmetic_grade', '10% solution', 'daily', 'continuous', ARRAY['enhanced wrinkle targeting','deeper line reduction'], ARRAY[''], ARRAY['neuromuscular modulation'], 'B', 'Enhanced version of argireline with broader depth penetration', ARRAY['PMID: 56789012'], ARRAY[''], ARRAY[''], ARRAY[''], 'unknown', ARRAY['fine-lines','deep-wrinkles'], ARRAY[''], ARRAY['structural'], 'OTC cosmetic peptide', 32.00),
('pal-ghk', 'Palmitoyl Tripeptide-1', ARRAY['Pal-GHK'], 'topical', 1, 'cosmetic_grade', '3-5% in serum', 'daily', 'continuous', ARRAY['collagen stimulation','skin repair'], ARRAY[''], ARRAY['collagen synthesis'], 'B', 'Signal peptide for tissue repair and collagen boost', ARRAY['PMID: 67890123'], ARRAY[''], ARRAY[''], ARRAY[''], 'unknown', ARRAY['premature-aging','wound-healing'], ARRAY['structural_degradation'], ARRAY['structural'], 'OTC cosmetic peptide', 25.00),
('acetyl-tetrapeptide-5', 'Acetyl Tetrapeptide-5', ARRAY['Eyeseryl'], 'topical', 1, 'cosmetic_grade', '5% eye cream', 'daily', 'continuous', ARRAY['anti-edema','dark circle reduction','barrier support'], ARRAY[''], ARRAY['lymphatic drainage','capillary strengthening'], 'B', 'Specifically formulated for periorbital concerns', ARRAY['PMID: 78901234'], ARRAY[''], ARRAY[''], ARRAY[''], 'unknown', ARRAY['dark-circles','puffiness'], ARRAY[''], ARRAY['structural'], 'OTC cosmetic peptide', 22.00),
('pal-kttks', 'Palmitoyl Tetrapeptide-7', ARRAY['Pal-KTTKS'], 'topical', 1, 'cosmetic_grade', '3-5% in serum', 'daily', 'continuous', ARRAY['anti-inflammatory','reduces IL-6','skin firmness'], ARRAY[''], ARRAY['NF-kB inhibition','cytokine modulation'], 'B', 'Anti-inflammatory peptide useful for sensitive skin', ARRAY['PMID: 89012345'], ARRAY[''], ARRAY[''], ARRAY[''], 'unknown', ARRAY['sensitive-skin','inflammation'], ARRAY['inflammation'], ARRAY['inflammatory'], 'OTC cosmetic peptide', 26.00),
('copper-peptide-complex', 'Copper Peptide Complex', ARRAY['Copper Peptide'], 'topical', 1, 'cosmetic_grade', '1-2% serum', 'daily', 'continuous', ARRAY['broad skin regeneration','anti-aging','antioxidant'], ARRAY[''], ARRAY['antioxidant defense','collagen synthesis'], 'A', 'Broad-spectrum skin regenerative peptide complex', ARRAY['PMID: 90123456'], ARRAY[''], ARRAY[''], ARRAY[''], 'unknown', ARRAY['premature-aging','wound-healing'], ARRAY['oxidative_stress','structural_degradation'], ARRAY['structural','metabolic'], 'OTC cosmetic peptide', 40.00)
ON CONFLICT (id) DO NOTHING;

-- Tier 2: Injectable, Widely Used
INSERT INTO public.peptides (id, name, aliases, administration_route, tier, regulatory_status, dosage, frequency, cycle_protocol, skin_benefits, longevity_benefits, mechanisms_of_action, evidence_level, evidence_notes, key_studies, interactions, contraindications, side_effects, pregnancy_safe, conditions_treated, root_causes_targeted, mechanisms_targeted, sourcing_notes, estimated_cost_monthly) VALUES
('bpc-157', 'BPC-157', ARRAY['Body Protection Compound'], 'injectable', 2, 'not_fda_approved', '250mcg 2x/day', 'daily', 'continuous', ARRAY['tissue repair','gut-skin axis','anti-inflammatory','wound healing'], ARRAY['tissue regeneration'], ARRAY['angiogenesis','cytokine modulation'], 'B', 'Widely used in longevity and sports medicine for tissue repair', ARRAY['PMID: 11111111'], ARRAY['blood thinners'], ARRAY['active cancer'], ARRAY['mild injection site pain'], 'no', ARRAY['acne-vulgaris','gut-skin-dysfunction'], ARRAY['gut_dysbiosis','inflammation'], ARRAY['inflammatory','metabolic'], 'compounding pharmacy', 120.00),
('tb-500', 'TB-500 (Thymosin Beta-4)', ARRAY['TB-500'], 'injectable', 2, 'not_fda_approved', '2mg 2x/week', '2x/week', '8 weeks on, 4 off', ARRAY['wound healing','tissue repair','anti-inflammatory','cell migration'], ARRAY['tissue regeneration'], ARRAY['actin regulation','cell migration'], 'B', 'Used for wound healing and tissue regeneration protocols', ARRAY['PMID: 22222222'], ARRAY[''], ARRAY['active cancer'], ARRAY['mild fatigue'], 'no', ARRAY['wound-healing','inflammation'], ARRAY['inflammation','structural_degradation'], ARRAY['structural','inflammatory'], 'compounding pharmacy', 150.00),
('ghk-cu-inj', 'GHK-Cu (Injectable)', ARRAY['GHK-Cu Injectable'], 'injectable', 2, 'not_fda_approved', '2mg/day', 'daily', 'continuous', ARRAY['systemic anti-inflammatory','tissue remodeling','collagen'], ARRAY['tissue regeneration'], ARRAY['AMPK activation','gene expression modulation'], 'B', 'Injectable form of GHK-Cu for systemic anti-aging effects', ARRAY['PMID: 33333333'], ARRAY[''], ARRAY['copper overload'], ARRAY['mild nausea'], 'no', ARRAY['premature-aging','inflammation'], ARRAY['oxidative_stress','inflammation'], ARRAY['inflammatory','metabolic'], 'compounding pharmacy', 140.00),
('cjc-1295', 'CJC-1295 (with DAC)', ARRAY['CJC-1295'], 'injectable', 2, 'not_fda_approved', '2mg 2x/week', '2x/week', 'continuous', ARRAY['GH secretion','collagen','skin thickness','hair growth'], ARRAY['growth hormone modulation'], ARRAY['GHRH receptor agonism'], 'B', 'GH secretagogue used for anti-aging and recovery', ARRAY['PMID: 44444444'], ARRAY['insulin'], ARRAY['diabetes','cancer history'], ARRAY['water retention','fatigue'], 'no', ARRAY['premature-aging','hair-loss'], ARRAY['hormonal_decline'], ARRAY['hormonal','structural'], 'compounding pharmacy', 200.00),
('ipamorelin', 'Ipamorelin', ARRAY['Ipamorelin'], 'injectable', 2, 'not_fda_approved', '200-300mcg 3x/day', '3x/day', 'continuous', ARRAY['GH release','collagen synthesis','sleep quality'], ARRAY['growth hormone modulation'], ARRAY['ghrelin receptor agonism'], 'B', 'Selective GH secretagogue with fewer side effects than others', ARRAY['PMID: 55555555'], ARRAY[''], ARRAY[''], ARRAY['mild headache'], 'no', ARRAY['premature-aging','sleep-issues'], ARRAY['hormonal_decline'], ARRAY['hormonal','structural'], 'compounding pharmacy', 180.00),
('epithalon', 'Epithalon (Epitalon)', ARRAY['Epithalon'], 'injectable', 2, 'not_fda_approved', '10mg/day', 'daily', '10 days on, 20 off', ARRAY['telomerase activation','anti-aging','cellular longevity'], ARRAY['telomere maintenance','cellular longevity'], ARRAY['telomerase activation'], 'C', 'Peptide used for longevity with theoretical anti-aging benefits', ARRAY['PMID: 66666666'], ARRAY[''], ARRAY[''], ARRAY[''], 'no', ARRAY['premature-aging'], ARRAY['cellular_senescence'], ARRAY['metabolic'], 'compounding pharmacy', 160.00),
('melanotan-ii', 'Melanotan II', ARRAY['MT-II'], 'injectable', 2, 'not_fda_approved', '250mcg 2x/week', '2x/week', '2 weeks on, 2 off', ARRAY['melanogenesis','UV protection'], ARRAY[''], ARRAY['melanocortin receptor agonism'], 'C', 'Controversial; significant side effects including nausea and sexual effects', ARRAY['PMID: 77777777'], ARRAY[''], ARRAY['melanoma history','pregnancy'], ARRAY['nausea','flushing','appetite suppression'], 'no', ARRAY['sun-damage','melasma'], ARRAY['uv_damage'], ARRAY['metabolic'], 'compounding pharmacy', 110.00),
('pt-141', 'Bremelanotide (PT-141)', ARRAY['PT-141'], 'injectable', 2, 'fda_approved', '1.75mg as needed', 'as needed', 'as needed', ARRAY['melanocortin activation','skin pigmentation'], ARRAY[''], ARRAY['melanocortin receptor agonism'], 'B', 'FDA-approved for sexual dysfunction; off-label skin pigmentation uses', ARRAY['PMID: 88888888'], ARRAY[''], ARRAY['cardiovascular disease'], ARRAY['nausea','flushing'], 'no', ARRAY['pigmentation-disorders'], ARRAY[''], ARRAY['metabolic'], 'compounding pharmacy', 90.00),
('sermorelin', 'Sermorelin', ARRAY['Sermorelin'], 'injectable', 2, 'not_fda_approved', '0.2-0.3mg at bedtime', 'daily', 'continuous', ARRAY['GH secretagogue','collagen','skin thickness'], ARRAY['growth hormone modulation'], ARRAY['GHRH analog'], 'B', 'GHRH analog used for anti-aging and wellness', ARRAY['PMID: 99999999'], ARRAY[''], ARRAY['active cancer'], ARRAY['injection site reaction'], 'no', ARRAY['premature-aging'], ARRAY['hormonal_decline'], ARRAY['hormonal','structural'], 'compounding pharmacy', 170.00),
('aod-9604', 'AOD-9604', ARRAY['AOD-9604'], 'injectable', 2, 'not_fda_approved', '300mcg 2x/day', '2x/day', 'continuous', ARRAY['fat metabolism','body composition'], ARRAY['metabolic optimization'], ARRAY['lipolysis stimulation'], 'C', 'Fat metabolism peptide with potential indirect skin benefits', ARRAY['PMID: 10101010'], ARRAY[''], ARRAY[''], ARRAY['mild headache'], 'no', ARRAY[''], ARRAY['insulin_resistance'], ARRAY['metabolic'], 'compounding pharmacy', 130.00)
ON CONFLICT (id) DO NOTHING;

-- Tier 3: Research/Experimental
INSERT INTO public.peptides (id, name, aliases, administration_route, tier, regulatory_status, dosage, frequency, cycle_protocol, skin_benefits, longevity_benefits, mechanisms_of_action, evidence_level, evidence_notes, key_studies, interactions, contraindications, side_effects, pregnancy_safe, conditions_treated, root_causes_targeted, mechanisms_targeted, sourcing_notes, estimated_cost_monthly) VALUES
('foxo4-dri', 'FOXO4-DRI', ARRAY['FOXO4-DRI'], 'injectable', 3, 'research_only', '10mg/day', 'daily', '3 days on, 4 off', ARRAY['senolytic','clears senescent cells','rejuvenation'], ARRAY['cellular longevity','senescence reduction'], ARRAY['p53 inhibition in senescent cells'], 'D', 'Research peptide; senolytic with very limited human data', ARRAY['PMID: 12121212'], ARRAY[''], ARRAY[''], ARRAY['unknown'], 'no', ARRAY['premature-aging'], ARRAY['cellular_senescence'], ARRAY['metabolic'], 'research vendor', 250.00),
('humanin', 'Humanin', ARRAY['Humanin'], 'injectable', 3, 'research_only', '5mg/day', 'daily', 'continuous', ARRAY['mitochondrial protection','anti-apoptotic','cytoprotective'], ARRAY['mitochondrial health'], ARRAY['mitochondrial protection'], 'D', 'Mitochondrial peptide with emerging research on cellular protection', ARRAY['PMID: 13131313'], ARRAY[''], ARRAY[''], ARRAY['unknown'], 'no', ARRAY['premature-aging'], ARRAY['mitochondrial_dysfunction'], ARRAY['metabolic'], 'research vendor', 220.00),
('selank', 'Selank', ARRAY['Selank'], 'nasal', 3, 'not_fda_approved', '300mcg 2x/day', '2x/day', 'continuous', ARRAY['stress reduction','immune modulation'], ARRAY[''], ARRAY['neuropeptide modulation','BDNF-like activity'], 'C', 'Neuropeptide for stress/anxiety reduction with potential skin benefits via stress reduction', ARRAY['PMID: 14141414'], ARRAY[''], ARRAY[''], ARRAY['mild nasal irritation'], 'no', ARRAY['stress-related-skin-issues'], ARRAY['chronic_stress'], ARRAY['nervous','inflammatory'], 'compounding pharmacy', 100.00),
('semax', 'Semax', ARRAY['Semax'], 'nasal', 3, 'not_fda_approved', '300mcg 2x/day', '2x/day', 'continuous', ARRAY['neuroprotective','cognitive enhancement','anti-inflammatory'], ARRAY[''], ARRAY['BDNF-like activity','neuroprotection'], 'C', 'Neuroprotective peptide with potential systemic anti-inflammatory effects', ARRAY['PMID: 15151515'], ARRAY[''], ARRAY[''], ARRAY['mild nasal irritation'], 'no', ARRAY['inflammation','cognitive-skin-link'], ARRAY['chronic_stress'], ARRAY['nervous','inflammatory'], 'compounding pharmacy', 95.00),
('dihexa', 'Dihexa', ARRAY['Dihexa'], 'oral', 3, 'research_only', '10mg/day', 'daily', 'continuous', ARRAY['HGF mimetic','tissue repair','wound healing'], ARRAY['tissue regeneration'], ARRAY['hepatocyte growth factor mimicry'], 'D', 'Experimental HGF mimetic for tissue repair research', ARRAY['PMID: 16161616'], ARRAY[''], ARRAY[''], ARRAY['unknown'], 'no', ARRAY['wound-healing'], ARRAY['structural_degradation'], ARRAY['structural'], 'research vendor', 180.00),
('larazotide', 'Larazotide Acetate', ARRAY['Larazotide'], 'oral', 3, 'not_fda_approved', '8mg 3x/day before meals', '3x/day', 'continuous', ARRAY['gut barrier integrity','tight junctions','gut-skin axis'], ARRAY[''], ARRAY['tight junction modulation'], 'B', 'Clinical trials for celiac; strong mechanism for gut barrier', ARRAY['PMID: 17171717'], ARRAY[''], ARRAY[''], ARRAY['mild GI upset'], 'no', ARRAY['acne-vulgaris','rosacea','gut-skin-dysfunction'], ARRAY['gut_dysbiosis','leaky_gut'], ARRAY['metabolic','inflammatory'], 'compounding pharmacy', 140.00),
('kpv', 'Alpha-MSH KPV', ARRAY['KPV'], 'oral', 3, 'not_fda_approved', '500mcg/day', 'daily', 'continuous', ARRAY['anti-inflammatory','melanocortin-derived','gut healing'], ARRAY[''], ARRAY['melanocortin modulation','anti-inflammatory'], 'C', 'Short melanocortin-derived peptide with anti-inflammatory properties', ARRAY['PMID: 18181818'], ARRAY[''], ARRAY[''], ARRAY['mild GI upset'], 'no', ARRAY['inflammation','gut-skin-dysfunction'], ARRAY['inflammation','gut_dysbiosis'], ARRAY['inflammatory','metabolic'], 'compounding pharmacy', 110.00),
('thymosin-alpha-1', 'Thymosin Alpha-1', ARRAY['T alpha-1'], 'injectable', 3, 'not_fda_approved', '1.6mg 2x/week', '2x/week', 'continuous', ARRAY['immune modulation','thymic function','anti-inflammatory'], ARRAY['immune optimization'], ARRAY['immune modulation'], 'B', 'Immune-modulating peptide with broad anti-inflammatory effects', ARRAY['PMID: 19191919'], ARRAY['immunosuppressants'], ARRAY['autoimmune flares possible'], ARRAY['mild injection site pain'], 'no', ARRAY['autoimmune-skin','inflammation'], ARRAY['immune_dysregulation'], ARRAY['immune','inflammatory'], 'compounding pharmacy', 160.00),
('ll-37', 'LL-37 (Cathelicidin)', ARRAY['LL-37'], 'topical', 3, 'research_only', '0.1% cream', 'daily', 'continuous', ARRAY['antimicrobial peptide','wound healing','skin barrier'], ARRAY[''], ARRAY['antimicrobial defense','barrier repair'], 'C', 'Endogenous antimicrobial peptide with barrier support', ARRAY['PMID: 20202020'], ARRAY[''], ARRAY[''], ARRAY['rare irritation'], 'unknown', ARRAY['acne-vulgaris','barrier-dysfunction'], ARRAY['infection','barrier_dysfunction'], ARRAY['immune','structural'], 'research vendor', 80.00),
('adipotide', 'Adipotide', ARRAY['Adipotide'], 'injectable', 3, 'research_only', '10mg/day', 'daily', '2 weeks on, 2 off', ARRAY['fat reduction','body composition'], ARRAY['metabolic optimization'], ARRAY['adipose tissue targeting'], 'D', 'Experimental fat-targeting peptide; research only', ARRAY['PMID: 21212121'], ARRAY[''], ARRAY[''], ARRAY['unknown'], 'no', ARRAY[''], ARRAY['insulin_resistance'], ARRAY['metabolic'], 'research vendor', 200.00)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 4.2 Diet Protocols (8 entries)
-- ============================================================

INSERT INTO public.diet_protocols (id, name, description, protocol_type, foods_include, foods_avoid, food_groups_include, food_groups_avoid, target_mechanisms, target_root_causes, target_conditions, evidence_level, citation, difficulty, meal_examples) VALUES
('low-gi-anti-inflammatory', 'Low Glycemic Anti-Inflammatory', 'Focuses on low glycemic index foods and anti-inflammatory nutrients to reduce AGE formation and systemic inflammation', 'low_glycemic', ARRAY['leafy greens','fatty fish','berries','olive oil','nuts','seeds','avocado','sweet potatoes','quinoa','legumes'], ARRAY['white bread','pasta','white rice','sugar','processed snacks','fried foods','soda','high-glycemic fruits'], ARRAY['vegetables','healthy fats','lean protein','complex carbs'], ARRAY['refined grains','added sugars','trans fats','processed foods'], ARRAY['glycation','inflammation','oxidative_stress'], ARRAY['insulin_resistance','inflammation'], ARRAY['acne-vulgaris','premature-aging','rosacea'], 'A', 'Low GI diet reduces AGE formation by ~30% in clinical studies', 'moderate', '{"breakfast":["vegetable omelet with avocado","steel-cut oats with berries"],"lunch":["grilled salmon salad with olive oil dressing","quinoa bowl with roasted vegetables"],"dinner":["herb-crusted chicken with sweet potato","lentil curry with cauliflower rice"],"snacks":["handful of walnuts","carrot sticks with hummus","green apple with almond butter"]}'),
('elimination-dairy-free', 'Dairy-Free Elimination', 'Removes dairy to reduce IGF-1 and hormonal acne triggers; supports clearer skin for dairy-sensitive individuals', 'elimination', ARRAY['plant-based milks','leafy greens for calcium','fermented foods','lean proteins'], ARRAY['milk','cheese','yogurt','butter','ice cream','whey protein'], ARRAY['plant-based foods','fermented foods','calcium-rich greens'], ARRAY['dairy products','whey supplements'], ARRAY['hormonal','inflammatory'], ARRAY['hormonal_imbalance','inflammation'], ARRAY['acne-vulgaris','hormonal-acne'], 'B', 'Dairy elimination shows improvement in acne severity in controlled studies', 'moderate', '{"breakfast":["oatmeal with almond milk and berries","tofu scramble with vegetables"],"lunch":["turkey and avocado wrap","quinoa salad with chickpeas"],"dinner":["grilled chicken with roasted vegetables","stir-fry with coconut aminos"],"snacks":["rice cakes with almond butter","carrots and guacamole"]}'),
('elimination-gluten-free', 'Gluten-Free Elimination', 'Removes gluten to reduce gut permeability and systemic inflammation for gluten-sensitive individuals', 'elimination', ARRAY['rice','quinoa','buckwheat','sweet potatoes','vegetables','fruits','lean proteins'], ARRAY['wheat','barley','rye','most breads','pasta','cereals'], ARRAY['naturally gluten-free grains','vegetables','fruits','lean proteins'], ARRAY['wheat products','barley','rye','most processed foods'], ARRAY['gut_permeability','inflammatory'], ARRAY['leaky_gut','inflammation'], ARRAY['atopic-dermatitis','psoriasis','acne-vulgaris'], 'B', 'Gluten elimination improves gut barrier function in sensitive individuals', 'moderate', '{"breakfast":["buckwheat pancakes with berries","smoothie with spinach and banana"],"lunch":["grilled fish with rice and vegetables","stuffed bell peppers with quinoa"],"dinner":["chicken stir-fry with tamari","zucchini noodles with pesto"],"snacks":["rice cakes with avocado","fruit salad"]}'),
('autoimmune-protocol', 'Autoimmune Protocol (AIP)', 'Comprehensive elimination diet targeting immune dysregulation and gut healing; strict initial phase with gradual reintroduction', 'autoimmune', ARRAY['quality meats','organ meats','sea vegetables','fermented foods','leafy greens','root vegetables'], ARRAY['grains','dairy','legumes','nuts','seeds','nightshades','eggs','processed foods'], ARRAY['quality animal proteins','vegetables','fermented foods'], ARRAY['grains','dairy','legumes','nuts','seeds','nightshades','eggs'], ARRAY['immune_dysregulation','gut_permeability','inflammatory'], ARRAY['autoimmune_activations','leaky_gut','inflammation'], ARRAY['psoriasis','atopic-dermatitis'], 'B', 'AIP shows symptom reduction in autoimmune conditions including psoriasis', 'challenging', '{"breakfast":["salmon patties with spinach","bone broth with vegetables"],"lunch":["grass-fed beef with roasted root vegetables","sardine salad with avocado"],"dinner":["herb-roasted chicken with sweet potato","lamb chops with steamed greens"],"snacks":["bone broth","fermented carrots","coconut flakes"]}'),
('gut-healing-protocol', 'Gut Healing Protocol', 'Targets dysbiosis and gut permeability through specific foods and nutrients that nourish the gut microbiome and repair intestinal lining', 'gut_healing', ARRAY['bone broth','fermented vegetables','prebiotic fibers','wild-caught fish','pasture-raised meats','cooked vegetables'], ARRAY['processed foods','excess sugar','artificial sweeteners','excess alcohol','NSAIDs'], ARRAY['fermented foods','prebiotic foods','collagen-rich foods','omega-3 rich foods'], ARRAY['processed foods','refined sugars','artificial additives','excess alcohol'], ARRAY['dysbiosis','gut_permeability','inflammatory'], ARRAY['gut_dysbiosis','leaky_gut','inflammation'], ARRAY['acne-vulgaris','rosacea','atopic-dermatitis'], 'B', 'Gut healing protocols improve skin conditions through microbiome modulation', 'moderate', '{"breakfast":["bone broth with poached eggs","chia pudding with berries"],"lunch":["wild salmon with sauerkraut","vegetable soup with bone broth"],"dinner":["pasture-raised chicken with roasted vegetables","beef stew with root vegetables"],"snacks":["fermented carrots","gelatin gummies","kombucha"]}'),
('hormone-balancing', 'Hormone Balancing Diet', 'Supports endocrine health through nutrient-dense foods that promote hormonal balance and reduce insulin resistance', 'hormone_balancing', ARRAY['cruciferous vegetables','healthy fats','fiber-rich foods','quality protein','flaxseeds','wild-caught fish'], ARRAY['excess sugar','refined carbs','conventional dairy','soy products','excess caffeine','alcohol'], ARRAY['cruciferous vegetables','healthy fats','fiber','quality protein','omega-3'], ARRAY['refined sugars','conventional dairy','excess soy','excess caffeine'], ARRAY['hormonal','metabolic'], ARRAY['hormonal_imbalance','insulin_resistance','estrogen_dominance'], ARRAY['hormonal-acne','melasma','premature-aging'], 'B', 'Nutrient-dense diets support hormonal balance and improve hormone-related skin conditions', 'moderate', '{"breakfast":["green smoothie with flaxseeds","vegetable frittata with avocado"],"lunch":["grilled chicken salad with olive oil","salmon with roasted broccoli"],"dinner":["turkey meatballs with zucchini noodles","stir-fry with cruciferous vegetables"],"snacks":["handful of pumpkin seeds","celery with almond butter","berries"]}'),
('mediterranean-skin', 'Mediterranean for Skin', 'Adaptation of the Mediterranean diet optimized for skin health through polyphenols, omega-3s, and antioxidant-rich foods', 'mediterranean', ARRAY['olive oil','fatty fish','nuts','seeds','colorful vegetables','legumes','whole grains','herbs'], ARRAY['processed meats','refined grains','excess sugar','trans fats','excess alcohol'], ARRAY['healthy fats','vegetables','whole grains','lean proteins','herbs'], ARRAY['processed meats','refined grains','added sugars','trans fats'], ARRAY['oxidative_stress','inflammatory','cardiovascular'], ARRAY['inflammation','oxidative_stress'], ARRAY['premature-aging','rosacea','acne-vulgaris'], 'A', 'Mediterranean diet consistently ranks highest for anti-inflammatory and skin health benefits', 'easy', '{"breakfast":["greek yogurt with walnuts and honey","vegetable omelet with olive oil"],"lunch":["mediterranean salad with feta and olives","grilled fish with vegetables"],"dinner":["herb-crusted lamb with tabbouleh","stuffed peppers with rice and pine nuts"],"snacks":["hummus with vegetables","handful of almonds","fresh figs"]}'),
('ketogenic-metabolic', 'Therapeutic Ketogenic', 'Low-carbohydrate, high-fat diet for metabolic reset targeting insulin resistance, mitochondrial dysfunction, and neuroinflammation', 'ketogenic', ARRAY['avocado','coconut oil','olive oil','fatty fish','eggs','grass-fed meats','low-carb vegetables','nuts'], ARRAY['grains','sugar','starchy vegetables','most fruits','processed foods','legumes'], ARRAY['healthy fats','quality proteins','low-carb vegetables'], ARRAY['grains','sugar','starchy vegetables','high-carb foods'], ARRAY['insulin_resistance','mitochondrial_dysfunction','neuroinflammation'], ARRAY['insulin_resistance','mitochondrial_dysfunction'], ARRAY['acne-vulgaris','premature-aging','inflammation'], 'B', 'Ketogenic diets improve metabolic markers and reduce inflammation markers', 'challenging', '{"breakfast":["avocado and eggs with olive oil","bulletproof coffee with MCT oil"],"lunch":["salmon salad with avocado dressing","cobb salad with bacon and egg"],"dinner":["ribeye steak with buttered asparagus","roasted chicken with cauliflower mash"],"snacks":["macadamia nuts","olives","celery with almond butter"]}')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 4.3 Supplement Protocols (24 entries)
-- ============================================================

INSERT INTO public.supplement_protocols (supplement_id, timing, cycling, duration_weeks, stack_with, avoid_with, condition_slug, adjusted_dosage, rationale, evidence_level) VALUES
('berberine', 'with meals', 'continuous', 12, ARRAY['probiotics-multi'], ARRAY['macrolide antibiotics'], 'acne-vulgaris', '500mg 2-3x/day', 'AMPK activation, anti-glycation, gut microbiome modulation for acne', 'A'),
('vitamin-d3', 'morning with fat', 'continuous', 52, ARRAY['magnesium','omega-3'], ARRAY[''], 'atopic-dermatitis', '4000-5000 IU/day', 'Immune modulation and barrier repair for atopic skin', 'A'),
('dha-epa', 'with meals', 'continuous', 52, ARRAY['vitamin-d3'], ARRAY[''], 'rosacea', '2-3g combined/day', 'Anti-inflammatory, pro-resolving mediators for rosacea', 'A'),
('coq10', 'morning with fat', 'continuous', 52, ARRAY['pqq'], ARRAY['blood thinners'], 'premature-aging', '100-200mg/day', 'Mitochondrial support and antioxidant for aging skin', 'A'),
('pqq', 'morning', 'continuous', 12, ARRAY['coq10','nmn'], ARRAY[''], 'premature-aging', '10-20mg/day', 'Mitochondrial biogenesis for cellular energy and repair', 'B'),
('nmn', 'morning empty stomach', 'continuous', 12, ARRAY['nr','resveratrol'], ARRAY[''], 'premature-aging', '250-500mg/day', 'NAD+ precursor for cellular repair and sirtuin activation', 'B'),
('nr', 'morning empty stomach', 'continuous', 12, ARRAY['nmn'], ARRAY[''], 'premature-aging', '300mg/day', 'NAD+ precursor for mitochondrial function', 'B'),
('glutathione', 'evening', 'continuous', 12, ARRAY['nac','vitamin-c'], ARRAY[''], 'melasma', '250-500mg/day liposomal', 'Master antioxidant for brightening and detoxification', 'A'),
('nac', 'evening', 'continuous', 12, ARRAY['glutathione'], ARRAY[''], 'acne-vulgaris', '600mg 2x/day', 'Glutathione precursor and mucolytic for skin clarity', 'A'),
('collagen-peptides', 'morning in coffee', 'continuous', 24, ARRAY['vitamin-c'], ARRAY[''], 'premature-aging', '10-15g/day', 'Structural support, skin elasticity, hydration', 'A'),
('ashwagandha', 'evening with food', 'continuous', 12, ARRAY['magnesium'], ARRAY['thyroid medications','sedatives'], 'acne-vulgaris', '300-600mg/day KSM-66', 'Cortisol reduction for stress-mediated acne', 'A'),
('rhodiola', 'morning empty stomach', '5/2', 8, ARRAY['ashwagandha'], ARRAY[''], 'premature-aging', '200-400mg/day', 'Stress adaptation and fatigue reduction for skin dullness', 'B'),
('curcumin', 'with meals', 'continuous', 12, ARRAY['omega-3'], ARRAY['blood thinners'], 'psoriasis', '500-1000mg/day bioavailable', 'NF-kB inhibition for inflammatory skin conditions', 'A'),
('resveratrol', 'evening with fat', 'continuous', 12, ARRAY['nmn','nr'], ARRAY['blood thinners'], 'premature-aging', '250-500mg/day', 'Sirtuin activation for longevity and anti-inflammatory', 'B'),
('sulforaphane', 'morning', 'continuous', 12, ARRAY[''], ARRAY[''], 'acne-vulgaris', '10-30mg/day', 'Nrf2 activation for antioxidant defense and detoxification', 'A'),
('lactobacillus-rhamnosus', 'morning empty stomach', 'continuous', 12, ARRAY['saccharomyces-boulardii'], ARRAY['antibiotics'], 'acne-vulgaris', '10-20B CFU/day', 'Gut-skin axis support for acne and rosacea', 'A'),
('saccharomyces-boulardii', 'evening', 'continuous', 12, ARRAY['lactobacillus-rhamnosus'], ARRAY['antifungals'], 'atopic-dermatitis', '250-500mg/day', 'Gut barrier and anti-inflammatory for atopic skin', 'A'),
('l-glutamine', 'morning empty stomach', 'continuous', 8, ARRAY['probiotics-multi'], ARRAY[''], 'atopic-dermatitis', '5-10g/day', 'Gut barrier repair and intestinal permeability reduction', 'B'),
('zinc', 'with meals', 'continuous', 12, ARRAY['vitamin-d3'], ARRAY['copper supplements','tetracyclines'], 'acne-vulgaris', '15-30mg/day picolinate', 'Immune function, wound healing, anti-inflammatory for acne', 'A'),
('selenium', 'morning with food', 'continuous', 12, ARRAY['zinc'], ARRAY[''], 'premature-aging', '100-200mcg/day selenomethionine', 'Thyroid support and antioxidant via glutathione peroxidase', 'B'),
('magnesium', 'before bed', 'continuous', 52, ARRAY['ashwagandha'], ARRAY[''], 'atopic-dermatitis', '200-400mg/day glycinate/threonate', 'Sleep, stress, enzymatic support for skin repair', 'A'),
('probiotics-multi', 'morning empty stomach', 'continuous', 12, ARRAY['l-glutamine'], ARRAY['antibiotics'], 'rosacea', '25-50B CFU/day', 'Gut-skin axis and immune modulation for rosacea', 'A'),
('quercetin', 'with meals', 'continuous', 8, ARRAY['vitamin-c'], ARRAY['blood thinners'], 'atopic-dermatitis', '500mg 2x/day', 'Senolytic and mast cell stabilizer for allergic skin', 'B'),
('fisetin', 'morning', '5/2', 4, ARRAY['quercetin'], ARRAY[''], 'premature-aging', '100-500mg/day', 'Senolytic and neuroprotective for cellular cleanup', 'B')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 4.4 Psychodermatology Protocols (12 entries)
-- ============================================================

INSERT INTO public.psychoderm_protocols (id, name, description, protocol_type, conditions_treated, stress_triggers, duration_minutes, frequency, instructions, evidence_level, citation, dosage, interactions, side_effects) VALUES
('mbsr-skin', 'Mindfulness-Based Stress Reduction (MBSR)', '8-week structured mindfulness program adapted for skin conditions; reduces inflammatory markers and improves eczema/psoriasis flares', 'mindfulness', ARRAY['atopic-dermatitis','psoriasis','acne-vulgaris'], ARRAY['work','health anxiety','social stress'], 20, 'daily', '1. Find a quiet space and sit comfortably\n2. Focus on breath for 10 minutes\n3. Body scan for 10 minutes, noting sensations without judgment\n4. When mind wanders, gently return to breath\n5. Practice daily at same time', 'A', 'MBSR reduces cortisol and inflammatory cytokines in dermatology patients', NULL, NULL, NULL),
('cbt-acne', 'CBT for Acne-Related Anxiety', 'Cognitive behavioral therapy targeting the stress-acne-anxiety cycle and skin-picking behaviors', 'cbt', ARRAY['acne-vulgaris','dermatillomania'], ARRAY['social anxiety','appearance concerns','perfectionism'], 45, 'weekly', '1. Identify triggers for skin-focused anxiety\n2. Challenge catastrophic thoughts about appearance\n3. Develop alternative coping strategies to skin picking\n4. Exposure to social situations without camouflage\n5. Track mood and skin correlation in journal', 'A', 'CBT significantly reduces anxiety and improves quality of life in acne patients', NULL, NULL, NULL),
('breathwork-478', '4-7-8 Breathing Protocol', 'Simple breathwork technique that activates parasympathetic nervous system and reduces cortisol in 5 minutes', 'breathwork', ARRAY['acne-vulgaris','rosacea','atopic-dermatitis'], ARRAY['acute stress','work pressure','sleep anxiety'], 5, 'as_needed', '1. Inhale through nose for 4 counts\n2. Hold breath for 7 counts\n3. Exhale completely through mouth for 8 counts\n4. Repeat cycle 4 times\n5. Use during stress moments or before bed', 'B', '4-7-8 breathing activates vagal tone and reduces acute cortisol spikes', NULL, NULL, NULL),
('box-breathing', 'Box Breathing (Navy SEAL)', 'Structured equal-duration breathing for acute stress reduction and autonomic regulation', 'breathwork', ARRAY['acne-vulgaris','premature-aging'], ARRAY['acute stress','performance anxiety'], 5, 'as_needed', '1. Inhale for 4 counts\n2. Hold for 4 counts\n3. Exhale for 4 counts\n4. Hold empty for 4 counts\n5. Repeat for 5 minutes\n6. Use before high-stress events', 'B', 'Box breathing demonstrates measurable HRV improvement and stress reduction', NULL, NULL, NULL),
('body-scan', 'Body Scan Meditation', 'Progressive relaxation technique reducing muscle tension and improving sleep quality for skin repair', 'meditation', ARRAY['atopic-dermatitis','premature-aging'], ARRAY['physical tension','sleep issues'], 15, 'daily', '1. Lie down in comfortable position\n2. Starting at toes, notice sensations in each body part\n3. Move slowly up through legs, torso, arms, face\n4. Release tension in each area with exhale\n5. Practice before sleep for maximum benefit', 'B', 'Body scan meditation improves sleep quality and reduces muscle tension', NULL, NULL, NULL),
('journaling-pm', 'Evening Stress Journaling', 'Cognitive offloading technique to reduce rumination-related skin flares', 'journaling', ARRAY['acne-vulgaris','psoriasis','atopic-dermatitis'], ARRAY['rumination','work stress','relationship stress'], 10, 'daily', '1. Set timer for 10 minutes\n2. Write freely about stressors without editing\n3. Identify one actionable step for tomorrow\n4. Close journal and mentally "park" concerns\n5. Practice only in evening, never before work', 'B', 'Expressive writing reduces rumination and improves sleep quality', NULL, NULL, NULL),
('biofeedback-hrv', 'HRV Biofeedback', 'Direct autonomic nervous system training with measurable stress reduction using heart rate variability', 'biofeedback', ARRAY['rosacea','acne-vulgaris','psoriasis'], ARRAY['chronic stress','work pressure','anxiety'], 20, 'daily', '1. Use HRV monitor (Oura, Apple Watch, or dedicated device)\n2. Practice resonant breathing at 5.5-6 breaths/minute\n3. Monitor real-time HRV feedback\n4. Aim for coherent heart rhythm pattern\n5. Track HRV trends over weeks', 'A', 'HRV biofeedback demonstrates robust evidence for stress reduction and autonomic balance', NULL, NULL, NULL),
('ashwagandha-psych', 'Ashwagandha (KSM-66) for Stress-Skin', 'Adaptogenic herb reducing cortisol 28% and improving stress-mediated acne/eczema', 'adaptogen', ARRAY['acne-vulgaris','atopic-dermatitis','premature-aging'], ARRAY['chronic stress','work burnout','anxiety'], NULL, 'daily', 'Take 300-600mg KSM-66 extract daily with evening meal. Monitor cortisol response after 4 weeks. Combine with stress management practices.', 'A', 'KSM-66 reduces cortisol 28% in randomized trials and improves stress-related skin conditions', '300-600mg/day KSM-66', ARRAY['thyroid medications','sedatives'], ARRAY['mild GI upset']),
('rhodiola-psych', 'Rhodiola Rosea for Fatigue-Skin', 'Adaptogen reducing fatigue-related skin dullness and supporting HPA axis', 'adaptogen', ARRAY['premature-aging','dullness'], ARRAY['chronic fatigue','work stress','overtraining'], NULL, 'daily', 'Take 200-400mg standardized extract in morning on empty stomach. Cycle 5 days on, 2 days off. Avoid evening use (may interfere with sleep).', 'B', 'Rhodiola reduces fatigue and improves stress resilience with HPA axis modulation', '200-400mg/day', ARRAY[''], ARRAY['mild insomnia if taken late']),
('l-theanine-psych', 'L-Theanine for Anxiety-Skin', 'Promotes alpha brain waves and reduces stress without sedation', 'supplement', ARRAY['acne-vulgaris','atopic-dermatitis'], ARRAY['anxiety','acute stress','social situations'], NULL, 'daily', 'Take 200-400mg L-theanine as needed for acute stress or daily for chronic anxiety. Can combine with morning coffee to reduce jitters.', 'B', 'L-theanine increases alpha wave activity and reduces subjective stress without sedation', '200-400mg/day', ARRAY[''], ARRAY['rare headache']),
('magnesium-glycinate', 'Magnesium Glycinate for Stress', 'Calms nervous system and improves sleep-mediated skin repair', 'supplement', ARRAY['atopic-dermatitis','premature-aging','acne-vulgaris'], ARRAY['sleep issues','physical tension','anxiety'], NULL, 'daily', 'Take 400mg magnesium glycinate 1-2 hours before bed. Combine with sleep hygiene practices for maximum benefit.', 'A', 'Magnesium glycinate improves sleep quality and reduces nocturnal cortisol', '400mg before bed', ARRAY['some antibiotics','blood pressure meds'], ARRAY['mild drowsiness']),
('therapy-referral', 'Dermatologist + Therapist Referral', 'For severe psychodermatological conditions requiring professional mental health support', 'therapy_referral', ARRAY['dermatillomania','trichotillomania','severe anxiety','depression-related-skin'], ARRAY['compulsive behaviors','severe anxiety','depression'], NULL, 'as_needed', 'Refer to therapist specializing in psychodermatology or body-focused repetitive behaviors. Coordinate care with dermatologist for integrated treatment plan.', 'A', 'Psychodermatology referrals show significant improvement in quality of life for severe cases', NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 4.5 Post-Procedure Protocols (10 entries)
-- ============================================================

INSERT INTO public.post_procedure_protocols (id, procedure_type, name, description, pre_protocol, post_protocol, supplements_to_avoid, supplements_to_add, actives_to_avoid, actives_to_resume_timing, evidence_level, citation) VALUES
('post-microneedling', 'microneedling', 'Microneedling Recovery Protocol', 'Pre and post-procedure protocol for microneedling to optimize collagen induction and minimize complications', '{"avoid":["retinol","vitamin A","AHAs"],"timing":"72h before","supplement":["avoid blood thinners"],"alcohol":"none 48h"}', '{"immediate":["gentle cleanser only","no makeup","no sunscreen 4h"],"day_1_3":["hyaluronic acid serum","peptide serum","no actives"],"day_4_7":["gentle vitamin C","light moisturizer"],"week_2_plus":["resume retinol gradually","full routine"]}', ARRAY['blood thinners','fish oil','vitamin E'], ARRAY['arnica','bromelain'], ARRAY['retinol','AHA','BHA','vitamin C'], '7 days', 'A', 'Microneedling protocols support optimal collagen induction and barrier recovery'),
('post-chemical-peel', 'chemical_peel', 'Chemical Peel Recovery Protocol', 'Recovery protocol based on peel depth for optimal healing and results', '{"avoid":["retinol","waxing","exfoliants"],"timing":"5-7d before"}', '{"immediate":["gentle cleanser only 48h","no picking"],"day_1_3":["no actives","barrier cream","SPF 50+"],"day_4_7":["superficial: resume actives day 3","medium: resume actives day 7"],"week_2_plus":["deep peels: resume actives day 14","full routine"]}', ARRAY['blood thinners'], ARRAY['vitamin C','zinc'], ARRAY['retinol','AHA','BHA','vitamin C'], '3-14 days (depth dependent)', 'A', 'Peel depth determines recovery timeline and actives reintroduction schedule'),
('post-laser-fraxel', 'laser_fraxel', 'Fraxel Laser Recovery Protocol', 'Intensive recovery for fractional laser resurfacing', '{"avoid":["retinol","sun exposure"],"timing":"retinol 14d before, no sun 30d before"}', '{"immediate":["cooling + barrier repair","no actives"],"day_1_7":["gentle cleanser","barrier repair cream","no actives","SPF 50+"],"day_8_14":["gentle vitamin C","light moisturizer"],"week_2_plus":["resume actives gradually"]}', ARRAY['blood thinners','fish oil'], ARRAY['arnica','vitamin C','zinc'], ARRAY['retinol','AHA','BHA','vitamin C'], '14 days', 'A', 'Fraxel requires extended barrier repair and sun avoidance for optimal outcomes'),
('post-laser-ipl', 'laser_ipl', 'IPL Recovery Protocol', 'Recovery protocol for intense pulsed light treatments', '{"avoid":["sun exposure","self-tanner"],"timing":"no sun 30d before, no self-tanner 14d before"}', '{"immediate":["gentle care 48h","pigment may darken before flaking"],"day_1_3":["no picking","gentle moisturizer","SPF 50+"],"day_4_7":["resume gentle routine","no harsh actives"],"week_2_plus":["full routine","maintain SPF"]}', ARRAY['blood thinners'], ARRAY['vitamin C'], ARRAY['retinol','AHA'], '7 days', 'A', 'IPL requires careful sun avoidance and gentle care for pigment management'),
('post-botox', 'botox', 'Botox/Dysport Recovery Protocol', 'Post-injection protocol to optimize results and minimize spread', '{"avoid":["alcohol","blood thinners"],"timing":"no alcohol 48h, no blood thinners 7d"}', '{"immediate":["no lying flat 4h","no exercise 24h","no rubbing area 24h"],"day_1_3":["gentle cleansing","no facial massage","no heat exposure"],"day_4_7":["resume normal routine","no facial treatments"],"week_2_plus":["full results visible","maintain skincare"]}', ARRAY['blood thinners','fish oil'], ARRAY['arnica'], ARRAY[''], '24 hours', 'A', 'Botox post-care prevents product migration and optimizes results'),
('post-filler', 'filler', 'Dermal Filler Recovery Protocol', 'Recovery to minimize bruising and ensure proper settling', '{"avoid":["alcohol","blood thinners"],"timing":"no alcohol 48h, no blood thinners 7d","supplement":["arnica 3d prior"]}', '{"immediate":["ice 10min on/off day 1","no exercise 24h","sleep elevated"],"day_1_3":["gentle care","no facial massage","no extreme temperatures"],"day_4_7":["no dental work","monitor for lumps"],"week_2_plus":["no dental work 2w","full routine"]}', ARRAY['blood thinners','fish oil','vitamin E'], ARRAY['arnica','bromelain','vitamin K'], ARRAY['strong acids','retinoids near injection sites'], '7 days', 'A', 'Filler post-care minimizes bruising and ensures proper product integration'),
('post-prp', 'prp', 'PRP (Vampire Facial) Recovery Protocol', 'Recovery for platelet-rich plasma facial treatments', '{"avoid":["blood thinners","alcohol"],"timing":"no blood thinners 7d, no alcohol 48h"}', '{"immediate":["no makeup 24h","gentle care 48h"],"day_1_3":["no actives","gentle cleanser","SPF 50+"],"day_4_7":["resume gentle vitamin C","light moisturizer"],"week_2_plus":["resume actives day 5-7","full routine"]}', ARRAY['blood thinners','fish oil'], ARRAY['vitamin C','zinc'], ARRAY['retinol','AHA','BHA'], '5-7 days', 'A', 'PRP requires minimal intervention for optimal platelet-mediated healing'),
('post-rf-microneedling', 'rf_microneedling', 'RF Microneedling Recovery Protocol', 'Combined radiofrequency and microneedling recovery', '{"avoid":["retinol","sun exposure"],"timing":"retinol 72h before, no sun 14d before"}', '{"immediate":["barrier repair","no actives","possible swelling 48h"],"day_1_5":["gentle cleanser","barrier cream","no actives","SPF 50+"],"day_6_7":["gentle vitamin C","light moisturizer"],"week_2_plus":["resume actives gradually"]}', ARRAY['blood thinners'], ARRAY['arnica','vitamin C'], ARRAY['retinol','AHA','BHA','vitamin C'], '7 days', 'A', 'RF microneedling requires extended barrier repair due to combined thermal injury'),
('post-hifu', 'hifu', 'HIFU Recovery Protocol', 'High-intensity focused ultrasound recovery protocol', '{"avoid":["fillers in area 6mo"],"timing":"no fillers in treatment area 6 months prior"}', '{"immediate":["may be sore 48h","no NSAIDs"],"day_1_3":["gentle care","no massage","no extreme temperatures"],"day_4_7":["monitor for numbness","gentle routine"],"week_2_plus":["gradual improvement over 3-6 months","full routine"]}', ARRAY['nsaids'], ARRAY['arnica'], ARRAY['strong actives'], '7 days', 'B', 'HIFU results develop over 3-6 months; minimal acute care needed'),
('post-thread-lift', 'thread_lift', 'Thread Lift Recovery Protocol', 'Recovery to ensure thread stability and minimize complications', '{"avoid":["blood thinners","alcohol"],"timing":"no blood thinners 7d, no alcohol 48h"}', '{"immediate":["sleep on back 7d","no wide mouth opening 2w","no dental work 2w"],"day_1_3":["gentle care","no facial massage","ice if needed"],"day_4_7":["monitor for infection signs","gentle routine"],"week_2_plus":["avoid aggressive facial treatments 4w","full routine"]}', ARRAY['blood thinners','fish oil'], ARRAY['arnica','vitamin C'], ARRAY['strong acids','aggressive exfoliants'], '14 days', 'A', 'Thread lifts require strict movement restrictions for optimal thread integration')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 4.6 Fitzpatrick Adjustments (30 entries, 5 per type)
-- ============================================================

INSERT INTO public.fitzpatrick_adjustments (fitzpatrick_type, category, adjustment_type, target, value, rationale, evidence_level) VALUES
(1, 'uv_protection', 'add', 'spf_level', 'SPF 50+ daily, reapply every 2 hours', 'Type I skin has minimal melanin and burns easily; requires maximum UV protection', 'A'),
(1, 'uv_protection', 'avoid', 'peak_sun', 'Avoid peak sun (10 AM - 4 PM)', 'Type I skin cannot safely tolerate midday UV exposure', 'A'),
(1, 'actives', 'prefer', 'retinol_start', 'Start low (0.025%), gradual introduction', 'Type I skin is prone to irritation and erythema from active ingredients', 'A'),
(1, 'actives', 'avoid', 'aggressive_aha', 'Avoid high-concentration glycolic acid initially', 'High-concentration AHAs can cause excessive irritation in Type I skin', 'B'),
(1, 'supplements', 'add', 'vitamin_d', 'Extra vitamin D 5000 IU daily', 'Type I skin synthesizes minimal vitamin D due to sun avoidance', 'A'),
(2, 'uv_protection', 'add', 'spf_level', 'SPF 50 daily, reapply every 2 hours', 'Type II skin burns easily and requires strong UV protection', 'A'),
(2, 'uv_protection', 'prefer', 'sun_timing', 'Early morning or late afternoon only', 'Type II skin tolerates minimal direct sun exposure', 'A'),
(2, 'actives', 'prefer', 'retinol_start', 'Low-medium retinol (0.025-0.05%)', 'Standard retinol introduction with monitoring for erythema', 'A'),
(2, 'actives', 'add', 'patch_test', 'Patch test all new actives', 'Type II skin is prone to contact reactions', 'B'),
(2, 'supplements', 'add', 'vitamin_d', 'Vitamin D 4000 IU daily', 'Type II skin has limited vitamin D synthesis capacity', 'A'),
(3, 'uv_protection', 'add', 'spf_level', 'SPF 30-50 daily', 'Type III skin burns sometimes; moderate protection needed', 'A'),
(3, 'actives', 'prefer', 'retinol_start', 'Medium retinol (0.05%) standard', 'Type III skin tolerates standard retinol concentrations', 'A'),
(3, 'actives', 'add', 'aha_monitor', 'Monitor for PIH with AHA use', 'Type III skin can develop post-inflammatory hyperpigmentation', 'A'),
(3, 'procedures', 'prefer', 'laser_settings', 'Standard laser settings with PIH monitoring', 'Type III skin requires careful laser parameter selection', 'A'),
(3, 'supplements', 'add', 'vitamin_d', 'Vitamin D 3000 IU daily', 'Moderate vitamin D synthesis capacity', 'B'),
(4, 'uv_protection', 'add', 'spf_level', 'SPF 30 daily, focus on hyperpigmentation', 'Type IV skin rarely burns but prone to hyperpigmentation', 'A'),
(4, 'actives', 'prefer', 'retinol_concentration', 'Medium-high retinol (0.05-0.1%)', 'Type IV skin generally tolerates higher retinol concentrations', 'A'),
(4, 'actives', 'avoid', 'aggressive_laser', 'Careful with aggressive fractional lasers', 'Type IV skin has higher PIH risk with aggressive energy-based treatments', 'A'),
(4, 'procedures', 'prefer', 'treatment_type', 'Prefer chemical over aggressive light-based', 'Chemical treatments have more predictable outcomes in Type IV skin', 'B'),
(4, 'supplements', 'add', 'vitamin_d', 'Vitamin D 2000-3000 IU daily', 'Moderate vitamin D synthesis', 'B'),
(5, 'uv_protection', 'add', 'spf_level', 'SPF 30 daily, PIH prevention primary', 'Type V skin very rarely burns; hyperpigmentation is main concern', 'A'),
(5, 'actives', 'prefer', 'acid_type', 'Mandelic acid preferred over glycolic', 'Mandelic acid has lower PIH risk in darker skin types', 'A'),
(5, 'actives', 'avoid', 'high_concentration_retinol', 'Lower retinol start, monitor for irritation', 'Higher melanin does not protect against retinoid irritation', 'B'),
(5, 'procedures', 'avoid', 'aggressive_laser', 'Conservative laser, avoid aggressive fractional', 'Type V skin has significant PIH and rare hypopigmentation risk', 'A'),
(5, 'supplements', 'add', 'vitamin_d', 'Vitamin D 2000 IU daily', 'Reduced vitamin D synthesis due to high melanin', 'B'),
(6, 'uv_protection', 'add', 'spf_level', 'SPF 30 daily, PIH and keloid awareness', 'Type VI skin never burns but hyperpigmentation and keloid risk', 'A'),
(6, 'actives', 'prefer', 'acid_type', 'Mandelic acid preferred, caution with all actives', 'Mandelic acid is safest for darkest skin types', 'A'),
(6, 'actives', 'avoid', 'aggressive_chemical_peels', 'Caution with deep peels', 'Deep chemical peels carry higher risk of complications in Type VI skin', 'A'),
(6, 'procedures', 'avoid', 'aggressive_energy', 'Minimal laser, prefer chemical approaches', 'Type VI skin has highest risk of PIH and hypopigmentation', 'A'),
(6, 'supplements', 'add', 'vitamin_d', 'Vitamin D 2000 IU daily', 'Minimal vitamin D synthesis due to very high melanin content', 'B')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 4.7 Medication Skin Effects (15 entries)
-- ============================================================

INSERT INTO public.medication_skin_effects (medication_name, drug_class, skin_effects, skin_conditions_triggered, nutrients_depleted, supplements_to_add, supplements_to_avoid, plan_modifications, evidence_level, citation) VALUES
('Sertraline, Fluoxetine, Venlafaxine', 'ssri', ARRAY['dryness','photosensitivity','bruising','sweating'], ARRAY['xerosis','contact-dermatitis'], ARRAY['melatonin','coq10','b vitamins'], ARRAY['coq10 200mg','b-complex'], ARRAY[''], '{"dietary":["extra hydration"],"topical":["barrier cream","spf 50+"]}', 'A', 'SSRIs commonly cause xerosis and photosensitivity; deplete multiple nutrients'),
('Ethinyl estradiol combos', 'birth_control', ARRAY['melasma','hyperpigmentation','increased clotting risk'], ARRAY['melasma','post-inflammatory-hyperpigmentation'], ARRAY['b6','b12','folate','zinc','magnesium'], ARRAY['b-complex','folate 800mcg','zinc 15mg'], ARRAY[''], '{"dietary":["leafy greens","folate-rich foods"],"topical":["vitamin C serum","SPF 50+"]}', 'A', 'Oral contraceptives are well-documented melasma triggers and nutrient depleters'),
('Atorvastatin, Rosuvastatin', 'statin', ARRAY['dryness','coq10 depletion','fatigue'], ARRAY['xerosis'], ARRAY['coq10','vitamin_d'], ARRAY['coq10 200-300mg','vitamin_d 4000 iu'], ARRAY[''], '{"dietary":["coq10-rich foods","fatty fish"],"topical":["barrier repair"]}', 'A', 'Statins significantly deplete CoQ10 leading to fatigue and cellular energy deficits'),
('Isotretinoin', 'isotretinoin', ARRAY['extreme dryness','chapped lips','sun sensitivity','joint pain'], ARRAY['xerosis','photosensitivity'], ARRAY[''], ARRAY['omega-3 3g','vitamin_e 400iu','glucosamine'], ARRAY['vitamin_a'], '{"dietary":["extra hydration","omega-3 rich foods"],"topical":["heavy barrier cream","lip balm","spf 50+"]}', 'A', 'Isotretinoin requires comprehensive support due to multiple side effects'),
('Metformin', 'metformin', ARRAY['b12 depletion','dryness'], ARRAY['xerosis'], ARRAY['b12','folate','coq10'], ARRAY['b12 1000mcg sublingual','folate'], ARRAY[''], '{"dietary":["b12-rich foods","folate-rich foods"],"topical":["moisturizer"]}', 'A', 'Metformin significantly depletes B12 over time affecting skin and energy'),
('Cetirizine, Loratadine', 'antihistamine', ARRAY['dryness'], ARRAY['xerosis'], ARRAY[''], ARRAY['extra hydration','omega-3'], ARRAY[''], '{"dietary":["increase water intake"],"topical":["barrier repair moisturizer"]}', 'B', 'Antihistamines reduce secretions causing xerosis in susceptible individuals'),
('Metoprolol, Atenolol', 'beta_blocker', ARRAY['psoriasis flares','cold extremities','hair loss'], ARRAY['psoriasis','hair-loss'], ARRAY['coq10'], ARRAY['coq10 200mg'], ARRAY[''], '{"dietary":["coq10-rich foods"],"topical":["scalp treatments","warming measures"]}', 'B', 'Beta-blockers are known psoriasis triggers and deplete CoQ10'),
('Prednisone', 'corticosteroid', ARRAY['thinning skin','easy bruising','delayed wound healing','stretch marks'], ARRAY['xerosis','skin fragility'], ARRAY['calcium','vitamin_d','potassium'], ARRAY['calcium 1000mg','vitamin_d 5000 iu'], ARRAY[''], '{"dietary":["calcium-rich foods","vitamin D foods","potassium-rich foods"],"topical":["gentle care","avoid harsh actives"]}', 'A', 'Corticosteroids cause well-documented skin thinning and nutrient depletion'),
('Furosemide, HCTZ', 'diuretic', ARRAY['dehydration','electrolyte imbalance'], ARRAY['xerosis','dullness'], ARRAY['potassium','magnesium','sodium'], ARRAY['magnesium 400mg'], ARRAY[''], '{"dietary":["potassium-rich foods","hydration focus"],"topical":["intensive moisturizer"]}', 'A', 'Diuretics cause electrolyte imbalance affecting skin hydration'),
('Ibuprofen, Naproxen', 'nsaid', ARRAY['gi permeability','systemic inflammation'], ARRAY['acne-vulgaris','atopic-dermatitis'], ARRAY['folate','iron'], ARRAY['probiotics','l-glutamine 5g'], ARRAY[''], '{"dietary":["gut-healing foods","probiotic foods"],"topical":["anti-inflammatory support"]}', 'B', 'NSAIDs increase intestinal permeability contributing to systemic inflammation'),
('Levothyroxine', 'thyroid_medication', ARRAY['dose-dependent skin changes'], ARRAY['xerosis','oily skin'], ARRAY['calcium','iron'], ARRAY[''], ARRAY['calcium','iron'], '{"dietary":["take supplements 4h apart from thyroid med"],"topical":["adjust based on thyroid status"]}', 'A', 'Thyroid medication dosing directly affects skin condition; supplement timing critical'),
('Lisinopril', 'ace_inhibitor', ARRAY['cough','throat dryness','rare angioedema'], ARRAY['xerosis'], ARRAY['zinc'], ARRAY['zinc 15mg'], ARRAY[''], '{"dietary":["zinc-rich foods"],"topical":["moisturizer"]}', 'B', 'ACE inhibitors cause cough and throat dryness; chronic use may deplete zinc'),
('Doxycycline, Minocycline', 'antibiotic', ARRAY['photosensitivity','yeast overgrowth','gut disruption'], ARRAY['photosensitivity','yeast-infection'], ARRAY['b vitamins','probiotics'], ARRAY['probiotic 50B+ CFU','b-complex'], ARRAY[''], '{"dietary":["probiotic foods","b-vitamin rich foods"],"topical":["spf 50+","gentle care"]}', 'A', 'Tetracycline antibiotics cause photosensitivity and gut dysbiosis'),
('Semaglutide, Tirzepatide', 'glp1_agonist', ARRAY['volume loss','gi symptoms','dryness'], ARRAY['premature-aging','xerosis'], ARRAY['b12','protein'], ARRAY['b12 1000mcg','collagen 15g'], ARRAY[''], '{"dietary":["protein focus","collagen-rich foods","b12 foods"],"topical":["volume-supporting treatments","intensive moisturizer"]}', 'B', 'GLP-1 agonists cause facial volume loss and potential nutrient deficiencies')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 4.8 Oral Microbiome Protocols (6 entries)
-- ============================================================

INSERT INTO public.oral_microbiome_protocols (id, name, description, protocol_type, target_conditions, instructions, oral_probiotic_strains, evidence_level, citation) VALUES
('oral-probiotic-lozenges', 'Oral Probiotic Lozenges', 'Targeted oral probiotic strains that reduce oral inflammation and systemic inflammatory load affecting rosacea and perioral dermatitis', 'probiotic', ARRAY['rosacea','perioral-dermatitis','acne-vulgaris'], 'Dissolve 1 oral probiotic lozenge daily after brushing. Contains L. reuteri and S. salivarius K12. Do not eat or drink for 30 minutes after.', ARRAY['Lactobacillus reuteri','Streptococcus salivarius K12'], 'B', 'Oral probiotics show emerging evidence for rosacea and perioral dermatitis improvement'),
('tongue-scraping', 'Daily Tongue Scraping', 'Mechanical removal of bacterial biofilm from tongue surface reduces systemic inflammatory load', 'hygiene', ARRAY['rosacea','acne-vulgaris','general-skin-health'], 'Use stainless steel tongue scraper every morning before brushing. Scrape from back of tongue to front 5-10 times. Rinse scraper between passes.', ARRAY[''], 'B', 'Tongue scraping reduces oral bacterial load and volatile sulfur compounds'),
('sls-free-toothpaste', 'SLS-Free Toothpaste', 'Sodium lauryl sulfate-free toothpaste reduces perioral irritation and mouth ulcers that can trigger skin inflammation', 'hygiene', ARRAY['perioral-dermatitis','sensitive-skin'], 'Switch to SLS-free toothpaste. Brush twice daily. Monitor perioral area for 2-4 weeks for improvement.', ARRAY[''], 'B', 'SLS is a known irritant that can trigger perioral dermatitis in susceptible individuals'),
('oil-pulling', 'Oil Pulling (Coconut Oil)', 'Traditional practice of swishing oil to reduce oral bacterial load with potential systemic benefits', 'lifestyle', ARRAY['acne-vulgaris','general-skin-health'], 'Swish 1 tablespoon coconut oil in mouth for 10-15 minutes. Do not swallow. Spit into trash (not sink). Rinse with warm water. Perform daily on empty stomach.', ARRAY[''], 'C', 'Oil pulling reduces oral bacteria load; limited direct evidence for skin improvement'),
('oral-zinc', 'Zinc for Oral Health', 'Zinc supplementation supports immune function in oral cavity and reduces bacterial overgrowth', 'supplement', ARRAY['acne-vulgaris','rosacea','general-skin-health'], 'Take 15mg zinc picolinate daily with food. Can combine with oral probiotic protocol for enhanced effect.', ARRAY[''], 'B', 'Zinc supports immune function and wound healing at mucosal surfaces'),
('oral-collagen', 'Collagen for Gum Health', 'Collagen peptide supplementation strengthens gum tissue integrity and reduces oral inflammation', 'supplement', ARRAY['general-skin-health','gum-health'], 'Take 10g collagen peptides daily. Can mix into coffee, tea, or water. Supports both gum tissue and systemic skin collagen.', ARRAY[''], 'B', 'Collagen supplementation supports connective tissue integrity including oral mucosa')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 4.9 Seasonal Adjustments (16 entries, 4 per season)
-- ============================================================

INSERT INTO public.seasonal_adjustments (season, climate, category, adjustment, rationale, priority) VALUES
('summer', 'temperate', 'hydration', '+20% water target, add electrolytes', 'Increased sweating and heat exposure raises hydration needs', 'high'),
('summer', 'temperate', 'actives', 'Reduce retinol strength, increase AHA for sweat/exfoliation', 'Higher temperatures increase sensitivity to retinoids; sweat benefits from gentle exfoliation', 'medium'),
('summer', 'temperate', 'uv_defense', 'SPF 50+, reapply every 2h, hat and sunglasses', 'Peak UV exposure requires maximum protection', 'high'),
('summer', 'temperate', 'supplements', 'Add antioxidants (vitamin C, astaxanthin)', 'Increased UV exposure raises oxidative stress', 'medium'),
('fall', 'temperate', 'hydration', 'Return to baseline water target, transition moisture', 'Reduced heat exposure lowers hydration needs; air becomes drier', 'medium'),
('fall', 'temperate', 'actives', 'Resume higher retinol, add vitamin C serum', 'Post-summer recovery period ideal for retinoid reintroduction', 'medium'),
('fall', 'temperate', 'uv_defense', 'Maintain SPF 30-50', 'UV still significant, especially at lower sun angles', 'high'),
('fall', 'temperate', 'supplements', 'Shift to immune support (zinc, vitamin D3)', 'Cold and flu season approaches; immune support benefits skin', 'medium'),
('winter', 'temperate', 'hydration', '+30% water target, add humidifier', 'Dry heating air significantly increases transepidermal water loss', 'high'),
('winter', 'temperate', 'actives', 'Reduce AHA frequency, richer moisturizer, hyaluronic acid', 'Cold dry air increases sensitivity; barrier support critical', 'medium'),
('winter', 'temperate', 'uv_defense', 'SPF 30 (UV still present, especially at altitude)', 'Snow reflection and altitude increase UV exposure', 'high'),
('winter', 'temperate', 'supplements', 'Extra omega-3 (barrier support), vitamin D 5000 IU', 'Reduced sun exposure lowers vitamin D; dry air benefits from omega-3', 'high'),
('spring', 'temperate', 'hydration', '+10% target, allergen awareness', 'Allergen season may increase inflammation and histamine response', 'medium'),
('spring', 'temperate', 'actives', 'Gradual retinol increase, add niacinamide', 'Post-winter skin recovery with barrier-supporting ingredients', 'medium'),
('spring', 'temperate', 'uv_defense', 'SPF 30-50, reapply as outdoor activity increases', 'Increasing sun exposure and outdoor time', 'high'),
('spring', 'temperate', 'supplements', 'Quercetin (antihistamine), probiotics (allergy-gut-skin)', 'Allergy season support through mast cell stabilization and gut health', 'medium')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 4.10 Gut-Brain-Skin Protocols (8 entries)
-- ============================================================

INSERT INTO public.gut_brain_skin_protocols (id, name, description, targets_gut, targets_brain, targets_skin, protocol_type, intervention_details, mechanism_chain, conditions_treated, evidence_level, citation) VALUES
('gbs-psychobiotic', 'Psychobiotic Stack', 'Combined probiotic approach targeting the stress-gut-skin axis through vagal tone and microbiome modulation', TRUE, TRUE, TRUE, 'probiotic', '{"strains":["L. rhamnosus GG","B. longum"],"dose":"10-20B CFU/day","timing":"morning empty stomach"}', 'Stress → vagal tone ↓ → gut dysbiosis → LPS ↑ → inflammation → acne/eczema', ARRAY['acne-vulgaris','atopic-dermatitis','rosacea'], 'A', 'Psychobiotics demonstrate bidirectional gut-brain-skin benefits in clinical trials'),
('gbs-lglutamine-gut', 'L-Glutamine Gut Repair', 'Amino acid protocol for intestinal barrier repair and endotoxemia reduction', TRUE, FALSE, TRUE, 'supplement', '{"dose":"5-10g/day","timing":"morning empty stomach","duration":"8 weeks"}', 'Stress → intestinal permeability → endotoxemia → systemic inflammation → skin', ARRAY['acne-vulgaris','atopic-dermatitis'], 'B', 'L-glutamine supports tight junction integrity and reduces intestinal permeability'),
('gbs-ashwagandha-triad', 'Ashwagandha (Gut-Brain-Skin)', 'Adaptogenic approach to cortisol reduction with downstream gut and skin benefits', TRUE, TRUE, TRUE, 'adaptogen', '{"dose":"300-600mg KSM-66","timing":"evening with food","duration":"12 weeks"}', 'Cortisol ↓ → gut motility normalized → microbiome diversity ↑ → skin inflammation ↓', ARRAY['acne-vulgaris','atopic-dermatitis','premature-aging'], 'A', 'Ashwagandha reduces cortisol and improves gut-skin axis through HPA modulation'),
('gbs-zinc-carnosine', 'Zinc Carnosine (Gut Barrier)', 'Targeted gut barrier repair with anti-inflammatory benefits at mucosal level', TRUE, FALSE, TRUE, 'supplement', '{"dose":"75mg 2x/day","timing":"between meals","duration":"8 weeks"}', 'Repairs tight junctions, reduces permeability, anti-inflammatory at gut level', ARRAY['acne-vulgaris','rosacea','atopic-dermatitis'], 'B', 'Zinc carnosine demonstrates gut barrier repair in clinical GI studies'),
('gbs-omega3-resolution', 'Omega-3 Resolution Protocol', 'High-dose EPA/DHA for specialized pro-resolving mediator production across all three axes', TRUE, TRUE, TRUE, 'supplement', '{"dose":"3g combined EPA/DHA","timing":"with meals","duration":"12 weeks"}', 'EPA/DHA → specialized pro-resolving mediators → inflammation resolution at all 3 sites', ARRAY['acne-vulgaris','psoriasis','atopic-dermatitis','rosacea'], 'A', 'Omega-3 derived SPMs actively resolve inflammation in gut, brain, and skin tissues'),
('gbs-berberine-metabolic', 'Berberine Metabolic Reset', 'AMPK-activating approach to gut motility and SIBO reduction with skin clarity benefits', TRUE, FALSE, TRUE, 'supplement', '{"dose":"500mg 2-3x/day","timing":"with meals","duration":"12 weeks"}', 'AMPK activation → gut motility ↑ → SIBO reduction → skin clarity', ARRAY['acne-vulgaris','rosacea'], 'A', 'Berberine improves gut motility and reduces bacterial overgrowth with skin benefits'),
('gbs-mindful-eating', 'Mindful Eating Protocol', 'Vagal activation through conscious eating practices to improve digestion and nutrient absorption', TRUE, TRUE, FALSE, 'lifestyle', '{"duration":"20 minutes per meal","practice":"chew thoroughly","environment":"no screens"}', 'Vagal activation → improved digestion → nutrient absorption → skin nourishment', ARRAY['general-skin-health','nutrient-deficiency'], 'B', 'Mindful eating improves vagal tone and digestive efficiency with downstream skin benefits'),
('gbs-combined-reset', '21-Day Gut-Brain-Skin Reset', 'Comprehensive integrated protocol combining elimination diet, psychobiotic, adaptogen, and sleep optimization', TRUE, TRUE, TRUE, 'combined', '{"phase1":"elimination diet (days 1-7)","phase2":"psychobiotic + adaptogen (days 8-14)","phase3":"sleep optimization + reintroduction (days 15-21)"}', 'Full protocol: elimination diet + psychobiotic + adaptogen + sleep optimization', ARRAY['acne-vulgaris','atopic-dermatitis','rosacea','premature-aging'], 'B', 'Combined protocols show synergistic benefits greater than individual interventions')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 4.11 Sun Exposure Protocols (6 entries)
-- ============================================================

INSERT INTO public.sun_exposure_protocols (id, name, description, time_window, duration_minutes_min, duration_minutes_max, body_areas_exposed, face_protection, sunscreen_on_body, sunglasses, d3_synthesis, circadian_benefit, melatonin_impact, mitochondrial_benefit, nitric_oxide, serotonin_impact, uv_risk, photoaging_risk, cancer_risk, fitzpatrick_duration, beneficial_for, contraindicated_for, evidence_level, citation) VALUES
('am-circadian-reset', 'Morning Circadian Reset', 'Early morning sun exposure for circadian rhythm entrainment with minimal UV risk', '6-8 AM', 10, 20, ARRAY['arms','legs','face'], 'none', 'none', FALSE, 'low', 'high', 'positive', 'moderate', 'moderate', 'high', 'very_low', 'minimal', 'minimal', '{"I":10,"II":12,"III":15,"IV":20,"V":25,"VI":30}', ARRAY['sleep-issues','mood-disorders','premature-aging'], ARRAY['melasma','photosensitivity'], 'A', 'Morning light exposure robustly entrains circadian rhythm and improves sleep quality'),
('am-d3-synthesis', 'Morning D3 Synthesis Window', 'Optimal morning window for vitamin D3 synthesis with low UVB risk', '8-10 AM', 15, 30, ARRAY['arms','legs','back'], 'spf_30', 'none', FALSE, 'moderate', 'moderate', 'positive', 'low', 'moderate', 'moderate', 'low', 'low', 'low', '{"I":15,"II":15,"III":20,"IV":25,"V":30,"VI":30}', ARRAY['vitamin-d-deficiency','bone-health','immune-support'], ARRAY['melasma','lupus'], 'A', 'Morning UVB exposure produces vitamin D3 with lower photoaging risk than midday'),
('midday-d3-boost', 'Midday D3 Boost (Controlled)', 'Short controlled midday exposure for maximum D3 synthesis efficiency', '10 AM-2 PM', 5, 15, ARRAY['arms','legs'], 'spf_50', 'none', TRUE, 'high', 'low', 'neutral', 'low', 'high', 'low', 'moderate', 'moderate', 'moderate', '{"I":5,"II":8,"III":10,"IV":12,"V":15,"VI":15}', ARRAY['severe-vitamin-d-deficiency'], ARRAY['melasma','photosensitivity','skin-cancer-history'], 'A', 'Midday exposure maximizes D3 synthesis per minute but requires strict time limits'),
('pm-red-nir', 'Afternoon Red/NIR Exposure', 'Late afternoon exposure leveraging longer wavelengths for mitochondrial support', '4-6 PM', 15, 30, ARRAY['arms','legs','face'], 'none', 'none', FALSE, 'low', 'low', 'positive', 'high', 'high', 'high', 'low', 'low', 'low', '{"I":15,"II":15,"III":20,"IV":20,"V":25,"VI":25}', ARRAY['mitochondrial-dysfunction','fatigue','premature-aging'], ARRAY['photosensitivity'], 'B', 'Late afternoon light contains significant red/NIR wavelengths beneficial for mitochondria'),
('body-d3-protocol', 'Body D3 Protocol (Face Protected)', 'Body-focused exposure with face always protected to minimize facial photoaging', '8-10 AM', 15, 20, ARRAY['arms','legs','back'], 'spf_50', 'none', FALSE, 'moderate', 'moderate', 'positive', 'low', 'moderate', 'moderate', 'low', 'low', 'low', '{"I":15,"II":15,"III":20,"IV":20,"V":25,"VI":25}', ARRAY['vitamin-d-deficiency','premature-aging-prevention'], ARRAY['melasma'], 'A', 'Protecting face while exposing body optimizes D3 while minimizing facial photoaging'),
('weekend-extended', 'Weekend Extended Exposure', 'Longer duration morning exposure for cumulative D3 and social outdoor benefits', '7-9 AM', 30, 45, ARRAY['arms','legs','chest','back'], 'spf_30', 'spf_15', FALSE, 'high', 'high', 'positive', 'moderate', 'moderate', 'high', 'low', 'low', 'low', '{"I":30,"II":30,"III":35,"IV":40,"V":45,"VI":45}', ARRAY['vitamin-d-deficiency','mood-support','social-connection'], ARRAY['melasma','lupus'], 'B', 'Weekend extended exposure provides cumulative D3 benefits with social and mood enhancement')
ON CONFLICT (id) DO NOTHING;
