-- SKINgenius: MECHANISM CHAINS (run after SEED-ALL-NEW-TABLES.sql)
INSERT INTO public.mechanism_chains (root_cause_id, mechanism_id, condition_id, description, evidence_level) VALUES
('follicular_hyperkeratinization','follicular_hyperkeratinization_mech','acne-vulgaris','Follicular hyperkeratinization affects skin through skin pathways leading to Acne Vulgaris','A'),
('increased_sebum_production','increased_sebum_production_mech','acne-vulgaris','Increased sebum production affects skin through hormones pathways leading to Acne Vulgaris','A'),
('c._acnes_colonization','c._acnes_colonization_mech','acne-vulgaris','C. acnes colonization affects skin through skin pathways leading to Acne Vulgaris','A'),
('inflammation','inflammation_mech','acne-vulgaris','Inflammation affects skin through skin pathways leading to Acne Vulgaris','A'),
('high_glycemic_diet','high_glycemic_diet_mech','acne-vulgaris','High glycemic diet affects skin through nutrition pathways leading to Acne Vulgaris','B'),
('gut_dysbiosis','gut_dysbiosis_mech','acne-vulgaris','Gut dysbiosis affects skin through gut pathways leading to Acne Vulgaris','D'),
('insulin_resistance','insulin_resistance_mech','acne-vulgaris','Insulin resistance affects skin through hormones pathways leading to Acne Vulgaris','B'),
('chronic_stress','chronic_stress_mech','acne-vulgaris','Chronic stress affects skin through lifestyle pathways leading to Acne Vulgaris','B'),
('androgen_excess','androgen_excess_mech','hormonal-acne','Androgen excess affects skin through hormones pathways leading to Hormonal Acne','A'),
('estrogen_fluctuations','estrogen_fluctuations_mech','hormonal-acne','Estrogen fluctuations affects skin through hormones pathways leading to Hormonal Acne','A'),
('insulin_resistance','insulin_resistance_mech','hormonal-acne','Insulin resistance affects skin through hormones pathways leading to Hormonal Acne','A'),
('cortisol_dysregulation','cortisol_dysregulation_mech','hormonal-acne','Cortisol dysregulation affects skin through hormones pathways leading to Hormonal Acne','B'),
('gut_dysbiosis','gut_dysbiosis_mech','hormonal-acne','Gut dysbiosis affects skin through gut pathways leading to Hormonal Acne','D'),
('mechanical_friction','mechanical_friction_mech','acne-mechanica','Mechanical friction affects skin through skin pathways leading to Acne Mechanica','A'),
('heat_and_occlusion','heat_and_occlusion_mech','acne-mechanica','Heat and occlusion affects skin through lifestyle pathways leading to Acne Mechanica','A'),
('pressure','pressure_mech','acne-mechanica','Pressure affects skin through lifestyle pathways leading to Acne Mechanica','A'),
('malassezia_overgrowth','malassezia_overgrowth_mech','fungal-acne','Malassezia overgrowth affects skin through skin pathways leading to Fungal Acne','A'),
('heat_and_humidity','heat_and_humidity_mech','fungal-acne','Heat and humidity affects skin through lifestyle pathways leading to Fungal Acne','A'),
('antibiotic_use','antibiotic_use_mech','fungal-acne','Antibiotic use affects skin through skin pathways leading to Fungal Acne','A'),
('immunosuppression','immunosuppression_mech','fungal-acne','Immunosuppression affects skin through lifestyle pathways leading to Fungal Acne','B'),
('systemic_corticosteroids','systemic_corticosteroids_mech','steroid-acne','Systemic corticosteroids affect skin through skin pathways leading to Steroid Acne','A'),
('anabolic_steroids','anabolic_steroids_mech','steroid-acne','Anabolic steroids affect skin through hormones pathways leading to Steroid Acne','A'),
('topical_steroid_overuse','topical_steroid_overuse_mech','steroid-acne','Topical steroid overuse affects skin through lifestyle pathways leading to Steroid Acne','A'),
('neurovascular_dysregulation','neurovascular_dysregulation_mech','rosacea','Neurovascular dysregulation affects skin through skin pathways leading to Rosacea','A'),
('demodex_mite_overgrowth','demodex_mite_overgrowth_mech','rosacea','Demodex mite overgrowth affects skin through skin pathways leading to Rosacea','B'),
('genetic_predisposition','genetic_predisposition_mech','rosacea','Genetic predisposition affects skin through skin pathways leading to Rosacea','B'),
('uv_damage','uv_damage_mech','rosacea','UV damage affects skin through lifestyle pathways leading to Rosacea','A'),
('barrier_dysfunction','barrier_dysfunction_mech','atopic-dermatitis','Barrier dysfunction affects skin through skin pathways leading to Atopic Dermatitis','A'),
('th2_immune_dysregulation','th2_immune_dysregulation_mech','atopic-dermatitis','Th2 immune dysregulation affects skin through immune pathways leading to Atopic Dermatitis','A'),
('environmental_allergens','environmental_allergens_mech','atopic-dermatitis','Environmental allergens affect skin through lifestyle pathways leading to Atopic Dermatitis','A'),
('microbiome_dysbiosis','microbiome_dysbiosis_mech','atopic-dermatitis','Microbiome dysbiosis affects skin through gut pathways leading to Atopic Dermatitis','A'),
('stress','stress_mech','atopic-dermatitis','Stress affects skin through lifestyle pathways leading to Atopic Dermatitis','A'),
('food_triggers','food_triggers_mech','atopic-dermatitis','Food triggers affect skin through nutrition pathways leading to Atopic Dermatitis','B'),
('irritant_exposure','irritant_exposure_mech','contact-dermatitis','Irritant exposure affects skin through lifestyle pathways leading to Contact Dermatitis','A'),
('allergic_sensitization','allergic_sensitization_mech','contact-dermatitis','Allergic sensitization affects skin through immune pathways leading to Contact Dermatitis','A'),
('sebaceous_gland_activity','sebaceous_gland_activity_mech','seborrheic-dermatitis','Sebaceous gland activity affects skin through hormones pathways leading to Seborrheic Dermatitis','A'),
('immune_response','immune_response_mech','seborrheic-dermatitis','Immune response affects skin through immune pathways leading to Seborrheic Dermatitis','A'),
('stress','stress_mech','seborrheic-dermatitis','Stress affects skin through lifestyle pathways leading to Seborrheic Dermatitis','A'),
('neurological_conditions','neurological_conditions_mech','seborrheic-dermatitis','Neurological conditions affect skin through lifestyle pathways leading to Seborrheic Dermatitis','B'),
('th1_th17_immune_dysregulation','th1_th17_immune_dysregulation_mech','psoriasis','Th1/Th17 immune dysregulation affects skin through immune pathways leading to Psoriasis','A'),
('genetic_predisposition','genetic_predisposition_mech','psoriasis','Genetic predisposition affects skin through skin pathways leading to Psoriasis','A'),
('environmental_triggers','environmental_triggers_mech','psoriasis','Environmental triggers affect skin through lifestyle pathways leading to Psoriasis','A'),
('obesity_metabolic_syndrome','obesity_metabolic_syndrome_mech','psoriasis','Obesity/metabolic syndrome affects skin through nutrition pathways leading to Psoriasis','A'),
('alcohol_and_smoking','alcohol_and_smoking_mech','psoriasis','Alcohol and smoking affect skin through lifestyle pathways leading to Psoriasis','A'),
('uv_radiation','uv_radiation_mech','melasma','UV radiation affects skin through lifestyle pathways leading to Melasma','A'),
('hormonal_factors','hormonal_factors_mech','melasma','Hormonal factors affect skin through hormones pathways leading to Melasma','A'),
('inflammatory_mediator_release','inflammatory_mediator_release_mech','post-inflammatory-hyperpigmentation','Inflammatory mediator release affects skin through immune pathways leading to Post-Inflammatory Hyperpigmentation','A'),
('melanocyte_activation','melanocyte_activation_mech','post-inflammatory-hyperpigmentation','Melanocyte activation affects skin through immune pathways leading to Post-Inflammatory Hyperpigmentation','A'),
('uv_exposure','uv_exposure_mech','post-inflammatory-hyperpigmentation','UV exposure affects skin through lifestyle pathways leading to Post-Inflammatory Hyperpigmentation','A'),
('chronic_uv_exposure','chronic_uv_exposure_mech','solar-lentigines','Chronic UV exposure affects skin through lifestyle pathways leading to Solar Lentigines','A'),
('melanocyte_proliferation','melanocyte_proliferation_mech','solar-lentigines','Melanocyte proliferation affects skin through immune pathways leading to Solar Lentigines','A'),
('autoimmune_destruction','autoimmune_destruction_mech','vitiligo','Autoimmune destruction affects skin through immune pathways leading to Vitiligo','A'),
('genetic_predisposition','genetic_predisposition_mech','vitiligo','Genetic predisposition affects skin through skin pathways leading to Vitiligo','A'),
('oxidative_stress','oxidative_stress_mech','vitiligo','Oxidative stress affects skin through immune pathways leading to Vitiligo','A'),
('koebner_phenomenon','koebner_phenomenon_mech','vitiligo','Koebner phenomenon affects skin through skin pathways leading to Vitiligo','A'),
('chronic_uv_exposure','chronic_uv_exposure_mech','actinic-keratosis','Chronic UV exposure affects skin through lifestyle pathways leading to Actinic Keratosis','A'),
('genetic_mutations','genetic_mutations_mech','skin-cancer-melanoma','Genetic mutations affect skin through skin pathways leading to Skin Cancer (Melanoma)','A'),
('uv_damage','uv_damage_mech','skin-cancer-melanoma','UV damage affects skin through lifestyle pathways leading to Skin Cancer (Melanoma)','A'),
('family_history','family_history_mech','skin-cancer-melanoma','Family history affects skin through skin pathways leading to Skin Cancer (Melanoma)','A'),
('many_nevi','many_nevi_mech','skin-cancer-melanoma','Many nevi affects skin through skin pathways leading to Skin Cancer (Melanoma)','A'),
('fluoride_toothpaste','fluoride_toothpaste_mech','perioral-dermatitis','Fluoride toothpaste affects skin through lifestyle pathways leading to Perioral Dermatitis','B'),
('cosmetics','cosmetics_mech','perioral-dermatitis','Cosmetics affect skin through skin pathways leading to Perioral Dermatitis','B'),
('topical_steroid_overuse','topical_steroid_overuse_mech','perioral-dermatitis','Topical steroid overuse affects skin through lifestyle pathways leading to Perioral Dermatitis','A'),
('keratin_overproduction','keratin_overproduction_mech','keratosis-pilaris','Keratin overproduction affects skin through skin pathways leading to Keratosis Pilaris','A'),
('dry_skin','dry_skin_mech','keratosis-pilaris','Dry skin affects skin through skin pathways leading to Keratosis Pilaris','A'),
('atopic_diathesis','atopic_diathesis_mech','keratosis-pilaris','Atopic diathesis affects skin through skin pathways leading to Keratosis Pilaris','B'),
('barrier_dysfunction','barrier_dysfunction_mech','xerosis','Barrier dysfunction affects skin through skin pathways leading to Xerosis','A'),
('low_humidity','low_humidity_mech','xerosis','Low humidity affects skin through lifestyle pathways leading to Xerosis','A'),
('aging','aging_mech','xerosis','Aging affects skin through skin pathways leading to Xerosis','A'),
('harsh_cleansers','harsh_cleansers_mech','xerosis','Harsh cleansers affect skin through lifestyle pathways leading to Xerosis','A'),
('hot_water','hot_water_mech','xerosis','Hot water affects skin through lifestyle pathways leading to Xerosis','A'),
('medical_conditions','medical_conditions_mech','xerosis','Medical conditions affect skin through skin pathways leading to Xerosis','B'),
('nutritional_deficiency','nutritional_deficiency_mech','xerosis','Nutritional deficiency affects skin through nutrition pathways leading to Xerosis','B'),
('over_exfoliation','over_exfoliation_mech','barrier-dysfunction','Over-exfoliation affects skin through lifestyle pathways leading to Barrier Dysfunction','A'),
('harsh_cleansers','harsh_cleansers_mech','barrier-dysfunction','Harsh cleansers affect skin through lifestyle pathways leading to Barrier Dysfunction','A'),
('environmental_damage','environmental_damage_mech','barrier-dysfunction','Environmental damage affects skin through lifestyle pathways leading to Barrier Dysfunction','A'),
('uv_damage','uv_damage_mech','barrier-dysfunction','UV damage affects skin through lifestyle pathways leading to Barrier Dysfunction','A'),
('hsv_1_reactivation','hsv_1_reactivation_mech','cold-sore','HSV-1 reactivation affects skin through skin pathways leading to Cold Sore','A'),
('stress','stress_mech','cold-sore','Stress affects skin through lifestyle pathways leading to Cold Sore','A'),
('uv_exposure','uv_exposure_mech','cold-sore','UV exposure affects skin through lifestyle pathways leading to Cold Sore','A'),
('hormonal_changes','hormonal_changes_mech','cold-sore','Hormonal changes affect skin through hormones pathways leading to Cold Sore','B'),
('curly_coily_hair','curly_coily_hair_mech','razor-bumps','Curly/coily hair affects skin through skin pathways leading to Razor Bumps','A'),
('close_shaving','close_shaving_mech','razor-bumps','Close shaving affects skin through lifestyle pathways leading to Razor Bumps','A'),
('pulling_skin_while_shaving','pulling_skin_while_shaving_mech','razor-bumps','Pulling skin while shaving affects skin through lifestyle pathways leading to Razor Bumps','A'),
('malassezia_overgrowth','malassezia_overgrowth_mech','tinea-versicolor','Malassezia overgrowth affects skin through skin pathways leading to Tinea Versicolor','A'),
('heat_and_humidity','heat_and_humidity_mech','tinea-versicolor','Heat and humidity affect skin through lifestyle pathways leading to Tinea Versicolor','A'),
('oily_skin','oily_skin_mech','tinea-versicolor','Oily skin affects skin through skin pathways leading to Tinea Versicolor','B'),
('bacterial_infection','bacterial_infection_mech','folliculitis','Bacterial infection affects skin through skin pathways leading to Folliculitis','A'),
('fungal_infection','fungal_infection_mech','folliculitis','Fungal infection affects skin through skin pathways leading to Folliculitis','A'),
('physical_irritation','physical_irritation_mech','folliculitis','Physical irritation affects skin through lifestyle pathways leading to Folliculitis','A'),
('ingrown_hairs','ingrown_hairs_mech','folliculitis','Ingrown hairs affect skin through skin pathways leading to Folliculitis','A'),
('hot_tub_exposure','hot_tub_exposure_mech','folliculitis','Hot tub exposure affects skin through lifestyle pathways leading to Folliculitis','A'),
('androgen_driven_sebaceous_lipogenesis','androgen_driven_sebaceous_lipogenesis_mech','excess-sebum-enlarged-pores','Androgen-driven sebaceous lipogenesis affects skin through hormones pathways leading to Excess Sebum and Enlarged Pores','A'),
('insulin_&_igf_1_upregulation','insulin_&_igf_1_upregulation_mech','excess-sebum-enlarged-pores','Insulin and IGF-1 upregulation affects skin through hormones pathways leading to Excess Sebum and Enlarged Pores','A'),
('high_glycemic_diet','high_glycemic_diet_mech','excess-sebum-enlarged-pores','High glycemic diet affects skin through nutrition pathways leading to Excess Sebum and Enlarged Pores','B'),
('dairy_&_whey_protein','dairy_&_whey_protein_mech','excess-sebum-enlarged-pores','Dairy and whey protein affects skin through nutrition pathways leading to Excess Sebum and Enlarged Pores','B'),
('follicular_hyperkeratinization','follicular_hyperkeratinization_mech','excess-sebum-enlarged-pores','Follicular hyperkeratinization affects skin through skin pathways leading to Excess Sebum and Enlarged Pores','A'),
('collagen_&_elastin_loss_(aging)','collagen_&_elastin_loss_(aging)_mech','excess-sebum-enlarged-pores','Collagen and elastin loss affects skin through skin pathways leading to Excess Sebum and Enlarged Pores','A'),
('chronic_stress','chronic_stress_mech','excess-sebum-enlarged-pores','Chronic stress affects skin through lifestyle pathways leading to Excess Sebum and Enlarged Pores','B'),
('dht_conversion','dht_conversion_mech','excess-sebum-enlarged-pores','DHT conversion affects skin through hormones pathways leading to Excess Sebum and Enlarged Pores','A')
ON CONFLICT (root_cause_id, mechanism_id, condition_id) DO UPDATE SET description=EXCLUDED.description, evidence_level=EXCLUDED.evidence_level;
