-- Root causes inserts
INSERT INTO public.root_causes (id, name, description, body_system, evidence_level) VALUES
  ('follicular_hyperkeratinization', 'Follicular hyperkeratinization', 'Abnormal desquamation of keratinocytes leading to microcomedone formation', 'immune', 'A'),
  ('increased_sebum_production', 'Increased sebum production', 'Androgen-driven sebaceous gland hyperplasia; DHT is primary mediator', 'hormonal', 'A'),
  ('c._acnes_colonization', 'C. acnes colonization', 'IA1 phylotype triggers inflammatory cascade via TLR2/TLR4', 'immune', 'A'),
  ('inflammation', 'Inflammation', 'Innate immune response to C. acnes and biofilm formation', 'immune', 'A'),
  ('high_glycemic_diet', 'High glycemic diet', 'High glycemic load increases IGF-1, stimulating sebum production', 'metabolic', 'B'),
  ('gut_dysbiosis', 'Gut dysbiosis', 'Gut-skin axis; dysbiosis may drive systemic inflammation', 'gut', 'D'),
  ('insulin_resistance', 'Insulin resistance', 'Hyperinsulinemia increases androgens and IGF-1', 'hormonal', 'B'),
  ('chronic_stress', 'Chronic stress', 'CRH/ACTH axis increases cortisol and androgens, stimulating sebum', 'nervous', 'B'),
  ('androgen_excess', 'Androgen excess', 'DHEA-S, testosterone, DHT drive sebum production', 'hormonal', 'A'),
  ('estrogen_fluctuations', 'Estrogen fluctuations', 'Mid-cycle and premenstrual estrogen drops worsen acne', 'hormonal', 'A'),
  ('cortisol_dysregulation', 'Cortisol dysregulation', 'Stress increases cortisol which increases androgens', 'hormonal', 'B'),
  ('mechanical_friction', 'Mechanical friction', 'Physical irritation disrupts follicular epithelium', 'immune', 'A'),
  ('heat_and_occlusion', 'Heat and occlusion', 'Traps sweat and sebum, promoting bacterial growth', 'nervous', 'A'),
  ('pressure', 'Pressure', 'Compresses follicles and increases inflammation', 'nervous', 'A'),
  ('malassezia_overgrowth', 'Malassezia overgrowth', 'Lipophilic yeast thrives in sebum-rich environments', 'immune', 'A'),
  ('heat_and_humidity', 'Heat and humidity', 'Promotes yeast proliferation', 'nervous', 'A'),
  ('antibiotic_use', 'Antibiotic use', 'Disrupts bacterial balance, allowing yeast overgrowth', 'immune', 'A'),
  ('immunosuppression', 'Immunosuppression', 'Reduced immune control of commensal yeast', 'nervous', 'B'),
  ('systemic_corticosteroids', 'Systemic corticosteroids', 'Prednisone and similar trigger sebaceous hyperplasia', 'immune', 'A'),
  ('anabolic_steroids', 'Anabolic steroids', 'Exogenous androgens increase sebum production', 'hormonal', 'A'),
  ('topical_steroid_overuse', 'Topical steroid overuse', 'Perioral and facial acneiform eruption', 'immune', 'A'),
  ('neurovascular_dysregulation', 'Neurovascular dysregulation', 'Abnormal blood vessel reactivity and inflammation', 'immune', 'A'),
  ('demodex_mite_overgrowth', 'Demodex mite overgrowth', 'Demodex folliculorum density higher in rosacea patients', 'immune', 'B'),
  ('genetic_predisposition', 'Genetic predisposition', 'Family history common; Celtic/Northern European ancestry', 'immune', 'B'),
  ('uv_damage', 'UV damage', 'Chronic sun exposure damages vessels and skin', 'nervous', 'A'),
  ('barrier_dysfunction', 'Barrier dysfunction', 'Filaggrin mutations; ceramide deficiency; increased TEWL', 'immune', 'A'),
  ('th2_immune_dysregulation', 'Th2 immune dysregulation', 'IL-4, IL-5, IL-13 drive inflammation and pruritus', 'immune', 'A'),
  ('environmental_allergens', 'Environmental allergens', 'Dust mites, pollen, pet dander trigger flares', 'nervous', 'A'),
  ('microbiome_dysbiosis', 'Microbiome dysbiosis', 'S. aureus overgrowth; reduced microbial diversity', 'immune', 'A'),
  ('stress', 'Stress', 'Stress worsens symptoms via HPA axis and immune modulation', 'nervous', 'A'),
  ('food_triggers', 'Food triggers', 'Dairy, eggs, wheat, soy in some patients', 'metabolic', 'B'),
  ('irritant_exposure', 'Irritant exposure', 'Detergents, solvents, acids, alkalis directly damage skin', 'immune', 'A'),
  ('allergic_sensitization', 'Allergic sensitization', 'Type IV hypersensitivity to specific allergens', 'immune', 'A'),
  ('sebaceous_gland_activity', 'Sebaceous gland activity', 'Androgen-driven sebum production feeds yeast', 'hormonal', 'A'),
  ('immune_response', 'Immune response', 'Individual susceptibility to Malassezia antigens', 'immune', 'A'),
  ('neurological_conditions', 'Neurological conditions', 'Parkinson''s disease increases risk', 'nervous', 'B'),
  ('th1_th17_immune_dysregulation', 'Th1/Th17 immune dysregulation', 'TNF-α, IL-17, IL-23 are key cytokines', 'immune', 'A'),
  ('environmental_triggers', 'Environmental triggers', 'Infection, trauma, stress, medications', 'nervous', 'A'),
  ('obesity_metabolic_syndrome', 'Obesity/metabolic syndrome', 'Adipokines promote inflammation; weight loss improves severity', 'metabolic', 'A'),
  ('alcohol_and_smoking', 'Alcohol and smoking', 'Exacerbate psoriasis and reduce treatment response', 'nervous', 'A'),
  ('uv_radiation', 'UV radiation', 'Stimulates melanocyte activity', 'nervous', 'A'),
  ('hormonal_factors', 'Hormonal factors', 'Estrogen, progesterone; pregnancy, OCPs, HRT', 'hormonal', 'A'),
  ('visible_light', 'Visible light', 'Contributes to pigmentation in darker skin', 'nervous', 'B'),
  ('thyroid_disease', 'Thyroid disease', 'Autoimmune thyroid disease association', 'hormonal', 'B'),
  ('inflammatory_mediator_release', 'Inflammatory mediator release', 'IL-1, TNF-α, GM-CSF stimulate melanocytes', 'immune', 'A'),
  ('melanocyte_activation', 'Melanocyte activation', 'Inflammation triggers melanin production', 'immune', 'A'),
  ('uv_exposure', 'UV exposure', 'Post-inflammatory skin is photosensitive; UV worsens PIH', 'nervous', 'A'),
  ('chronic_uv_exposure', 'Chronic UV exposure', 'Cumulative sun damage; UVA primarily responsible', 'nervous', 'A'),
  ('melanocyte_proliferation', 'Melanocyte proliferation', 'Increased melanocyte number and melanin', 'immune', 'A'),
  ('dna_damage', 'DNA damage', 'UV-induced p53 mutations in keratinocytes', 'immune', 'A'),
  ('autoimmune_destruction', 'Autoimmune destruction', 'CD8+ T-cells target melanocytes', 'immune', 'A'),
  ('oxidative_stress', 'Oxidative stress', 'Excessive H2O2 in epidermis; defective catalase', 'immune', 'A'),
  ('koebner_phenomenon', 'Koebner phenomenon', 'Trauma initiates new lesions', 'immune', 'A'),
  ('genetic_mutations', 'Genetic mutations', 'BRAF, NRAS, CDKN2A mutations', 'immune', 'A'),
  ('family_history', 'Family history', '10% have familial melanoma', 'immune', 'A'),
  ('many_nevi', 'Many nevi', '>50 common nevi increases risk', 'immune', 'A'),
  ('fluoride_toothpaste', 'Fluoride toothpaste', 'Can trigger or exacerbate', 'nervous', 'B'),
  ('cosmetics', 'Cosmetics', 'Heavy moisturizers, occlusive products', 'immune', 'B'),
  ('keratin_overproduction', 'Keratin overproduction', 'Excess keratin blocks hair follicles', 'immune', 'A'),
  ('dry_skin', 'Dry skin', 'Worse in winter; improves with humidity', 'immune', 'A'),
  ('atopic_diathesis', 'Atopic diathesis', 'Associated with atopic dermatitis', 'immune', 'B'),
  ('low_humidity', 'Low humidity', 'Winter, indoor heating, desert climates', 'nervous', 'A'),
  ('aging', 'Aging', 'Decreased sebum, ceramides, and natural moisturizing factors', 'immune', 'A'),
  ('harsh_cleansers', 'Harsh cleansers', 'Strip natural lipids', 'nervous', 'A'),
  ('hot_water', 'Hot water', 'Strips lipids and damages barrier', 'nervous', 'A'),
  ('medical_conditions', 'Medical conditions', 'Hypothyroidism, diabetes, kidney disease', 'immune', 'B'),
  ('nutritional_deficiency', 'Nutritional deficiency', 'Essential fatty acids, vitamins A, D, E', 'metabolic', 'B'),
  ('sun_exposure', 'Sun exposure', 'Contributes to development', 'nervous', 'B'),
  ('oily_skin', 'Oily skin', 'Malassezia thrives on sebum', 'immune', 'B'),
  ('bacterial_infection', 'Bacterial infection', 'S. aureus most common', 'immune', 'A'),
  ('fungal_infection', 'Fungal infection', 'Malassezia, dermatophytes', 'immune', 'A'),
  ('physical_irritation', 'Physical irritation', 'Shaving, friction, tight clothing', 'nervous', 'A'),
  ('ingrown_hairs', 'Ingrown hairs', 'Curly hair re-enters skin; pseudofolliculitis barbae', 'immune', 'A'),
  ('hot_tub_exposure', 'Hot tub exposure', 'Pseudomonas folliculitis', 'nervous', 'A'),
  ('hsv_1_reactivation', 'HSV-1 reactivation', 'Latent virus in trigeminal ganglion reactivates', 'immune', 'A'),
  ('hormonal_changes', 'Hormonal changes', 'Menstrual cycle, pregnancy', 'hormonal', 'B'),
  ('curly_coily_hair', 'Curly/coily hair', 'Hair re-enters skin after shaving; foreign body reaction', 'immune', 'A'),
  ('close_shaving', 'Close shaving', 'Multi-blade razors cut hair below skin surface', 'nervous', 'A'),
  ('pulling_skin_while_shaving', 'Pulling skin while shaving', 'Causes hair to snap back below surface', 'nervous', 'A'),
  ('androgen_driven_sebaceous_lipogenesis', 'Androgen-driven sebaceous lipogenesis', 'DHT is the primary mediator of sebaceous gland activity; testosterone converts to DHT via 5-alpha reductase at the skin level', 'hormonal', 'A'),
  ('insulin_&_igf_1_upregulation', 'Insulin & IGF-1 upregulation', 'Spikes in insulin and Insulin-like Growth Factor 1 directly upregulate sebum production via androgen pathway', 'hormonal', 'A'),
  ('dairy_&_whey_protein', 'Dairy & whey protein', 'Dairy (especially whey) increases IGF-1 levels, amplifying androgen-driven sebum production', 'metabolic', 'B'),
  ('collagen_&_elastin_loss_(aging)', 'Collagen & elastin loss (aging)', 'Decreased collagen and elastin around pore openings reduces structural support, making pores appear larger', 'immune', 'A'),
  ('dht_conversion', 'DHT conversion', 'Testosterone converts to more potent DHT via 5-alpha reductase, amplifying sebum production signal', 'hormonal', 'A'),
  ('over_exfoliation', 'Over-exfoliation', 'Excessive use of acids, retinoids, or physical scrubs damages barrier', 'nervous', 'A'),
  ('environmental_damage', 'Environmental damage', 'Pollution, wind, cold weather damage barrier lipids', 'nervous', 'A');

-- Total: 86 root causes
