// ============================================================================
// COLORgenius Unified Integration Layer — Data Models
// Version: 1.0.0
// Description: TypeScript interfaces mapping Square + Vagaro → unified domain
// ============================================================================

// ─────────────────────────────────────────────────────────────────────────────
// Shared / Core Types
// ─────────────────────────────────────────────────────────────────────────────

/** Supported external platforms */
export type Platform = 'square' | 'vagaro';

/** Sync status for every unified record */
export type SyncStatus = 'synced' | 'pending' | 'conflict' | 'error' | 'ignored';

/** OAuth state for a connected merchant */
export type ConnectionStatus = 'connected' | 'disconnected' | 'refresh_needed' | 'revoked';

/** Generic externally-sourced IDs */
export interface PlatformIds {
  square?: string | null;
  vagaro?: string | null;
}

/** Timestamp metadata auto-generated by the gateway */
export interface SyncMeta {
  createdAt: string;           // ISO 8601
  updatedAt: string;           // ISO 8601
  lastSyncedAt: string | null; // ISO 8601
  syncStatus: SyncStatus;
  sourcePlatform: Platform;    // Which platform last modified this record
  version: number;             // Optimistic-locking / conflict detection
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. UnifiedCustomer
// ─────────────────────────────────────────────────────────────────────────────

/** Normalised contact info (deduplicated across platforms) */
export interface UnifiedContact {
  email: string | null;
  phone: string | null;        // E.164 normalised
  phoneCountryCode: string | null;
}

/** A single customer entity unified across Square + Vagaro */
export interface UnifiedCustomer {
  id: string;                  // UUIDv4 — COLORgenius canonical ID

  // ── Identity ──
  firstName: string;
  lastName: string;
  displayName: string;
  dateOfBirth: string | null;  // ISO 8601 date
  gender: 'male' | 'female' | 'non_binary' | 'prefer_not_to_say' | null;
  notes: string;

  // ── Contact ──
  contact: UnifiedContact;
  secondaryEmails: string[];   // Historical / duplicate emails found
  secondaryPhones: string[];   // Historical / duplicate phones found

  // ── Platform linkage ──
  platformIds: PlatformIds;
  platformRaw: Record<Platform, Record<string, unknown>>; // Stash full payload

  // ── Salon context ──
  salonId: string;             // COLORgenius salon tenant
  firstVisitDate: string | null;
  lastVisitDate: string | null;
  totalVisits: number;
  lifetimeSpendCents: number;  // Normalised to minor currency units
  preferredStylistId: string | null;
  tags: string[];

  // ── Marketing / consent ──
  emailMarketingConsent: boolean;
  smsMarketingConsent: boolean;
  birthYearForMarketing: number | null; // Derived, not DOB

  // ── Merge metadata ──
  mergedFrom: string[];        // List of UnifiedCustomer IDs merged into this one
  mergeConfidence: number;       // 0.0–1.0 score from identity resolution

  // ── Sync ──
  sync: SyncMeta;
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. UnifiedAppointment
// ─────────────────────────────────────────────────────────────────────────────

/** Appointment lifecycle states */
export type AppointmentStatus =
  | 'booked'
  | 'confirmed'
  | 'checked_in'
  | 'in_progress'
  | 'completed'
  | 'cancelled'
  | 'no_show'
  | 'rescheduled';

/** A single service line-item inside an appointment */
export interface AppointmentServiceLine {
  id: string;                  // UUID
  unifiedServiceId: string;    // FK → UnifiedService
  platformServiceId: string;   // Raw platform service ID
  serviceName: string;
  stylistId: string | null;    // FK → UnifiedEmployee
  stylistName: string | null;
  durationMinutes: number;
  priceCents: number;
  startTime: string;           // ISO 8601
  endTime: string;             // ISO 8601
  colorFormulaRef: string | null; // FK → ColorFormula (COLORgenius extension)
}

/** Unified appointment — bookable unit of work */
export interface UnifiedAppointment {
  id: string;                  // UUIDv4

  // ── Participants ──
  salonId: string;
  customerId: string;          // FK → UnifiedCustomer
  customerName: string;        // Denormalised for quick display

  // ── Timing ──
  startTime: string;           // ISO 8601
  endTime: string;             // ISO 8601
  timezone: string;            // IANA tz (e.g. America/New_York)
  checkedInAt: string | null;
  completedAt: string | null;

  // ── Services ──
  services: AppointmentServiceLine[];
  totalDurationMinutes: number;
  totalPriceCents: number;

  // ── Status ──
  status: AppointmentStatus;
  cancellationReason: string | null;
  cancellationSource: Platform | 'manual' | null;

  // ── Platform linkage ──
  platformIds: PlatformIds;
  platformRaw: Record<Platform, Record<string, unknown>>;

  // ── Salon extensions ──
  roomId: string | null;
  chairId: string | null;
  isRecurring: boolean;
  recurrenceRule: string | null; // iCal RRULE string
  parentAppointmentId: string | null; // For reschedules / recurrences

  // ── Sync ──
  sync: SyncMeta;
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. UnifiedTransaction
// ─────────────────────────────────────────────────────────────────────────────

/** Transaction line-item types */
export type TransactionLineType = 'service' | 'product' | 'tip' | 'discount' | 'tax' | 'fee' | 'gift_card' | 'other';

/** Payment tender types */
export type TenderType = 'cash' | 'card' | 'gift_card' | 'store_credit' | 'check' | 'other' | 'external';

/** A single line on a receipt */
export interface TransactionLineItem {
  id: string;
  type: TransactionLineType;
  unifiedServiceId: string | null;   // FK → UnifiedService (if service)
  unifiedProductId: string | null;   // FK → UnifiedInventory (if product)
  name: string;                      // Denormalised display name
  quantity: number;
  unitPriceCents: number;
  discountCents: number;
  taxCents: number;
  totalCents: number;
  employeeId: string | null;         // FK → UnifiedEmployee (who performed/sold)
  colorFormulaRef: string | null;
}

/** Payment tender record */
export interface TransactionTender {
  id: string;
  type: TenderType;
  amountCents: number;
  tipCents: number;
  cardLastFour: string | null;
  cardBrand: string | null;          // visa, mastercard, etc.
  processedAt: string;               // ISO 8601
  externalTransactionId: string | null; // Square/Vagaro payment ID
}

/** Unified POS transaction / receipt */
export interface UnifiedTransaction {
  id: string;                        // UUIDv4

  // ── Context ──
  salonId: string;
  customerId: string | null;         // FK → UnifiedCustomer
  customerName: string | null;
  appointmentId: string | null;      // FK → UnifiedAppointment

  // ── Line items ──
  lines: TransactionLineItem[];
  tenders: TransactionTender[];

  // ── Totals ──
  subtotalCents: number;
  discountTotalCents: number;
  taxTotalCents: number;
  tipTotalCents: number;
  totalCents: number;

  // ── Refunds ──
  refundedTotalCents: number;
  refundLines: TransactionLineItem[];

  // ── Metadata ──
  receiptNumber: string;
  receiptUrl: string | null;
  invoiceId: string | null;
  note: string;

  // ── Platform linkage ──
  platformIds: PlatformIds;
  platformRaw: Record<Platform, Record<string, unknown>>;

  // ── Sync ──
  sync: SyncMeta;
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. UnifiedInventory
// ─────────────────────────────────────────────────────────────────────────────

/** Inventory item types */
export type InventoryItemType = 'product' | 'color' | 'developer' | 'treatment' | 'tool' | 'retail' | 'other';

/** Stock tracking unit */
export interface InventorySku {
  sku: string;
  barcode: string | null;
  supplierSku: string | null;
}

/** Stock level at a specific location / salon */
export interface StockLevel {
  locationId: string;
  quantityOnHand: number;
  quantityReserved: number;    // For appointments / pending orders
  quantityAvailable: number;   // Computed: onHand - reserved
  reorderPoint: number;
  reorderQuantity: number;
  lastCountedAt: string | null;
}

/** Unified product / inventory item */
export interface UnifiedInventory {
  id: string;                        // UUIDv4

  // ── Identity ──
  name: string;
  description: string;
  type: InventoryItemType;
  categoryId: string | null;         // FK → UnifiedCategory
  brand: string | null;

  // ── SKUs ──
  identifiers: InventorySku;
  alternativeSkus: string[];         // Historical SKUs from merges

  // ── Pricing ──
  basePriceCents: number;
  costCents: number | null;          // Average / last cost
  msrpCents: number | null;

  // ── Stock ──
  stock: StockLevel[];               // Per-location tracking
  isTracked: boolean;                // false = non-tracked service/consumable

  // ── Variants ──
  variantName: string | null;        // e.g. "8oz", "32oz", "Light Ash Blonde"
  parentProductId: string | null;    // FK → UnifiedInventory (variant parent)
  variantAttributes: Record<string, string>; // { size: "8oz", shade: "5N" }

  // ── Salon context ──
  salonId: string;
  supplierId: string | null;
  supplierName: string | null;

  // ── Platform linkage ──
  platformIds: PlatformIds;
  platformRaw: Record<Platform, Record<string, unknown>>;

  // ── Sync ──
  sync: SyncMeta;
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. UnifiedService
// ─────────────────────────────────────────────────────────────────────────────

/** Service category taxonomy (salon-specific) */
export type ServiceCategory =
  | 'hair_color'
  | 'hair_cut'
  | 'hair_treatment'
  | 'hair_styling'
  | 'hair_extension'
  | 'hair_removal'
  | 'skin_treatment'
  | 'nail_service'
  | 'consultation'
  | 'other';

/** Service sub-type for colour work */
export type ColorServiceType =
  | 'full_color'
  | 'root_touchup'
  | 'balayage'
  | 'highlights'
  | 'double_process'
  | 'color_correction'
  | 'gloss_toner'
  | 'vivid_fashion'
  | 'other_color';

/** Processing requirements for a service */
export interface ServiceProcessing {
  averageDurationMinutes: number;
  minDurationMinutes: number;
  maxDurationMinutes: number;
  requiresPatchTest: boolean;
  patchTestHoursBefore: number | null;
}

/** Unified salon service — the thing clients book */
export interface UnifiedService {
  id: string;                        // UUIDv4

  // ── Identity ──
  name: string;
  description: string;
  category: ServiceCategory;
  colorType: ColorServiceType | null;

  // ── Pricing ──
  basePriceCents: number;
  variablePricing: boolean;          // e.g. colour by-the-ounce
  priceRangeCents: [number, number] | null; // [min, max] if variable

  // ── Duration ──
  processing: ServiceProcessing;

  // ── Booking rules ──
  bookableOnline: boolean;
  requiresConsultationFirst: boolean;
  maxGuestsPerSlot: number;        // 1 for most, >1 for group classes
  bufferMinutesAfter: number;        // Cleanup / reset time

  // ── Resources ──
  requiredRoomType: string | null;   // e.g. "color_bar", "shampoo_station"
  requiredEquipment: string[];       // e.g. ["steamer", "color_cart"]

  // ── Salon context ──
  salonId: string;
  employeeIds: string[];             // Which stylists can perform

  // ── Platform linkage ──
  platformIds: PlatformIds;
  platformRaw: Record<Platform, Record<string, unknown>>;

  // ── Sync ──
  sync: SyncMeta;
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. Supporting / Cross-Cutting Models
// ─────────────────────────────────────────────────────────────────────────────

/** Unified employee / stylist record */
export interface UnifiedEmployee {
  id: string;
  salonId: string;
  firstName: string;
  lastName: string;
  displayName: string;
  email: string | null;
  phone: string | null;
  role: 'owner' | 'manager' | 'stylist' | 'assistant' | 'receptionist' | 'other';
  specialties: ServiceCategory[];
  bio: string;
  isActive: boolean;
  platformIds: PlatformIds;
  sync: SyncMeta;
}

/** Platform connection record (OAuth token storage) */
export interface PlatformConnection {
  id: string;
  salonId: string;
  platform: Platform;
  status: ConnectionStatus;

  // OAuth tokens (encrypted at rest)
  accessToken: string;               // Encrypted
  refreshToken: string;              // Encrypted
  tokenExpiresAt: string;            // ISO 8601
  tokenScope: string[];

  // Webhook config
  webhookSecret: string | null;      // Encrypted — for signature verification
  webhookEndpointUrl: string | null; // Our endpoint registered with platform
  webhookEventsSubscribed: string[];

  // Merchant info
  platformMerchantId: string;
  platformMerchantName: string;
  platformLocationId: string | null;

  // Sync state
  lastSyncAt: string | null;
  lastSyncCursor: string | null;     // Pagination / delta token
  initialSyncCompleted: boolean;

  sync: SyncMeta;
}

/** Identity match candidate (intermediate resolution result) */
export interface IdentityMatchCandidate {
  confidence: number;                // 0.0–1.0
  sourceCustomerId: string;          // Platform customer ID
  targetUnifiedCustomerId: string;   // Existing unified record (or null for new)
  matchedFields: ('email' | 'phone' | 'name' | 'dob')[],
  fieldScores: {
    email: number;
    phone: number;
    name: number;
    dob: number;
  };
  recommendation: 'link' | 'merge' | 'create_new' | 'review';
}

/** Webhook envelope — normalised before queuing */
export interface WebhookEnvelope {
  id: string;                        // UUID — our idempotency key
  platform: Platform;
  eventType: string;                   // Normalised event name
  receivedAt: string;                  // ISO 8601
  payload: Record<string, unknown>;    // Raw JSON body
  signature: string | null;
  processedAt: string | null;
  processingResult: 'success' | 'error' | 'ignored' | 'pending' | null;
  retryCount: number;
  lastError: string | null;
}

/** Audit log entry for every sync operation */
export interface SyncAuditLog {
  id: string;
  timestamp: string;                   // ISO 8601
  salonId: string;
  platform: Platform;
  operation: 'push' | 'pull' | 'webhook' | 'resolve' | 'merge' | 'retry';
  entityType: 'customer' | 'appointment' | 'transaction' | 'inventory' | 'service' | 'employee';
  entityId: string;                  // Unified ID
  platformEntityId: string;          // External ID
  status: 'success' | 'error' | 'conflict' | 'skipped';
  details: Record<string, unknown>;
  errorMessage: string | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// 7. API Request/Response Types
// ─────────────────────────────────────────────────────────────────────────────

/** Paginated list wrapper */
export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    cursor: string | null;           // Opaque cursor for next page
    hasMore: boolean;
    totalCount: number | null;     // Null if counting is expensive
  };
}

/** Unified query filters */
export interface CustomerFilter {
  salonId: string;
  query?: string;                    // Name/email/phone fuzzy search
  email?: string;
  phone?: string;
  lastVisitAfter?: string;
  lastVisitBefore?: string;
  tags?: string[];
  syncStatus?: SyncStatus;
}

export interface AppointmentFilter {
  salonId: string;
  customerId?: string;
  stylistId?: string;
  startAfter?: string;
  startBefore?: string;
  status?: AppointmentStatus;
}

export interface TransactionFilter {
  salonId: string;
  customerId?: string;
  appointmentId?: string;
  after?: string;
  before?: string;
  minAmountCents?: number;
  maxAmountCents?: number;
}

/** Identity resolution request */
export interface IdentityResolutionRequest {
  salonId: string;
  platform: Platform;
  platformCustomerId: string;
  customerData: {
    firstName: string;
    lastName: string;
    email: string | null;
    phone: string | null;
    dateOfBirth: string | null;
  };
}

export interface IdentityResolutionResponse {
  candidates: IdentityMatchCandidate[];
  selectedAction: 'link' | 'merge' | 'create_new' | 'review';
  resolvedUnifiedId: string | null;
}

/** Manual merge request */
export interface ManualMergeRequest {
  salonId: string;
  sourceIds: string[];               // UnifiedCustomer IDs to merge
  targetId: string;                  // Which record to keep as canonical
  conflictResolution: Record<string, 'source' | 'target' | 'manual'>; // Field-level override
}

// ─────────────────────────────────────────────────────────────────────────────
// 8. Webhook-Specific Types
// ─────────────────────────────────────────────────────────────────────────────

/** Normalised event names (platform-agnostic) */
export type UnifiedEventType =
  // Customers
  | 'customer.created'
  | 'customer.updated'
  | 'customer.deleted'
  // Appointments
  | 'appointment.created'
  | 'appointment.updated'
  | 'appointment.cancelled'
  | 'appointment.completed'
  | 'appointment.checked_in'
  // Transactions
  | 'transaction.created'
  | 'transaction.updated'
  | 'transaction.refunded'
  // Inventory
  | 'inventory.updated'
  | 'inventory.stock_changed'
  // Services
  | 'service.created'
  | 'service.updated'
  | 'service.deleted'
  // Connection
  | 'connection.healthy'
  | 'connection.disconnected'
  | 'connection.sync_started'
  | 'connection.sync_completed';

/** Platform-to-unified event mapping config */
export interface EventMapping {
  platform: Platform;
  platformEvent: string;
  unifiedEvent: UnifiedEventType;
  entityType: 'customer' | 'appointment' | 'transaction' | 'inventory' | 'service' | 'connection';
  extractor: string;                   // Reference to transformer function name
}

// ============================================================================
// EOF
// ============================================================================
