/**
 * Facial Aesthetics — Improvement Catalog Seed Data
 *
 * 60+ improvement items across 7 categories.
 * Each item includes feature targeting, score impact, cost, timeline, and evidence.
 *
 * Categories:
 * - Topical/Skincare (9 items)
 * - Devices/Tools (5 items)
 * - Lifestyle (6 items)
 * - Supplements (7 items)
 * - Peptides (5 items)
 * - Injectables/Procedures (12 items)
 *
 * Usage: Import and seed into aesthetic_improvements table.
 */

import { AestheticImprovement } from "@/types/facial-aesthetics";

// =============================================================================
// TOPICAL / SKINCARE (9 items)
// =============================================================================

const TOPICAL_IMPROVEMENTS: AestheticImprovement[] = [
  {
    id: "topical-retinol-05",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Retinol 0.5%",
    category: "topical",
    invasiveness: "none",
    score_impact: 15.0,
    confidence: 0.85,
    timeline_weeks: 10,
    cost_min: 35.0,
    cost_max: 55.0,
    recurring: true,
    recurring_cost_monthly: 45.0,
    evidence_level: "A",
    evidence_notes:
      "Retinoids increase collagen synthesis, reduce fine lines, improve texture. Meta-analysis of 16 RCTs confirms efficacy.",
    key_studies: ["PMID:22091568", "PMID:25897529"],
    ingredient_ids: ["retinol", "retinyl-palmitate"],
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: {
      south_asian:
        "Start with 0.3% to minimize irritation; azelaic acid can be combined",
      east_asian:
        "Lower concentration often sufficient due to generally thinner stratum corneum",
      african:
        "Higher melanin provides natural photo-protection but SPF 50+ still essential",
    },
    fitzpatrick_adjustments: {
      type_5_6:
        "Use encapsulated retinol to reduce irritation risk; monitor for post-inflammatory hyperpigmentation",
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "topical-vitamin-c",
    feature: "skin",
    sub_feature: "pigmentation_evenness",
    name: "Vitamin C Serum (L-Ascorbic Acid 15%)",
    category: "topical",
    invasiveness: "none",
    score_impact: 10.0,
    confidence: 0.8,
    timeline_weeks: 6,
    cost_min: 25.0,
    cost_max: 45.0,
    recurring: true,
    recurring_cost_monthly: 35.0,
    evidence_level: "A",
    evidence_notes:
      "L-Ascorbic acid inhibits tyrosinase, reduces oxidative stress, brightens skin.",
    key_studies: ["PMID:18296368", "PMID:17311065"],
    ingredient_ids: ["l-ascorbic-acid"],
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: {
      south_asian:
        "Excellent for PIH prevention; combine with niacinamide for enhanced effect",
    },
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "topical-niacinamide-5",
    feature: "skin",
    sub_feature: "pore_visibility",
    name: "Niacinamide 5%",
    category: "topical",
    invasiveness: "none",
    score_impact: 8.0,
    confidence: 0.82,
    timeline_weeks: 5,
    cost_min: 15.0,
    cost_max: 30.0,
    recurring: true,
    recurring_cost_monthly: 22.0,
    evidence_level: "A",
    evidence_notes:
      "Reduces sebum production, minimizes pore appearance, strengthens barrier.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: ["niacinamide"],
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "topical-azelaic-acid",
    feature: "skin",
    sub_feature: "pigmentation_evenness",
    name: "Azelaic Acid 10%",
    category: "topical",
    invasiveness: "none",
    score_impact: 12.0,
    confidence: 0.78,
    timeline_weeks: 8,
    cost_min: 20.0,
    cost_max: 40.0,
    recurring: true,
    recurring_cost_monthly: 30.0,
    evidence_level: "A",
    evidence_notes:
      "Tyrosinase inhibitor, anti-inflammatory, treats acne and rosacea simultaneously.",
    key_studies: ["PMID:25897529"],
    ingredient_ids: ["azelaic-acid"],
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: {
      south_asian:
        "Preferred over hydroquinone for melasma; safer for long-term use",
      african: "Excellent for PIH; gentler than hydroquinone",
    },
    fitzpatrick_adjustments: {
      type_5_6: "Safer than hydroquinone; minimal risk of ochronosis",
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "topical-spf-50",
    feature: "skin",
    sub_feature: "pigmentation_evenness",
    name: "SPF 50 Daily Sunscreen",
    category: "topical",
    invasiveness: "none",
    score_impact: 8.0,
    confidence: 0.9,
    timeline_weeks: 4,
    cost_min: 15.0,
    cost_max: 30.0,
    recurring: true,
    recurring_cost_monthly: 22.0,
    evidence_level: "A",
    evidence_notes:
      "Prevents photoaging, hyperpigmentation, and UV-induced collagen breakdown.",
    key_studies: ["PMID:25897529", "PMID:18296368"],
    ingredient_ids: ["zinc-oxide", "titanium-dioxide", "avobenzone"],
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: {
      type_5_6:
        "Use mineral SPF to avoid chemical filter irritation; may leave white cast",
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "topical-retinol-eye",
    feature: "eyes",
    sub_feature: "under_eye_hollowness",
    name: "Retinol Eye Cream",
    category: "topical",
    invasiveness: "none",
    score_impact: 6.0,
    confidence: 0.7,
    timeline_weeks: 10,
    cost_min: 30.0,
    cost_max: 60.0,
    recurring: true,
    recurring_cost_monthly: 45.0,
    evidence_level: "B",
    evidence_notes:
      "Low-concentration retinol improves periorbital skin texture and thickness.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: ["retinol"],
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "topical-vitamin-k-eye",
    feature: "eyes",
    sub_feature: "under_eye_pigmentation",
    name: "Vitamin K Cream (Under-Eye)",
    category: "topical",
    invasiveness: "none",
    score_impact: 5.0,
    confidence: 0.65,
    timeline_weeks: 6,
    cost_min: 25.0,
    cost_max: 40.0,
    recurring: true,
    recurring_cost_monthly: 32.0,
    evidence_level: "B",
    evidence_notes:
      "Vitamin K may reduce vascular discoloration under eyes. Limited RCT data.",
    key_studies: ["PMID:17311065"],
    ingredient_ids: ["vitamin-k"],
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "topical-ha-lips",
    feature: "lips",
    sub_feature: "fullness",
    name: "Hyaluronic Acid Lip Treatment",
    category: "topical",
    invasiveness: "none",
    score_impact: 7.0,
    confidence: 0.72,
    timeline_weeks: 3,
    cost_min: 20.0,
    cost_max: 35.0,
    recurring: true,
    recurring_cost_monthly: 27.0,
    evidence_level: "B",
    evidence_notes:
      "HA draws moisture to lip surface, creating temporary plumping effect.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: ["hyaluronic-acid"],
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "topical-castor-brows",
    feature: "brow",
    sub_feature: "fullness",
    name: "Castor Oil / Peptide Brow Serum",
    category: "topical",
    invasiveness: "none",
    score_impact: 8.0,
    confidence: 0.6,
    timeline_weeks: 12,
    cost_min: 15.0,
    cost_max: 30.0,
    recurring: true,
    recurring_cost_monthly: 22.0,
    evidence_level: "C",
    evidence_notes:
      "Ricinoleic acid in castor oil may promote hair growth. Peptide serums show promise in small studies.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: ["castor-oil", "ricinoleic-acid"],
    supplement_ids: null,
    peptide_ids: ["tb4-fragmax"],
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// =============================================================================
// DEVICES / TOOLS (5 items)
// =============================================================================

const DEVICE_IMPROVEMENTS: AestheticImprovement[] = [
  {
    id: "device-gua-sha",
    feature: "jaw",
    sub_feature: "definition",
    name: "Gua Sha (Lymphatic Drainage)",
    category: "device",
    invasiveness: "none",
    score_impact: 6.0,
    confidence: 0.6,
    timeline_weeks: 3,
    cost_min: 20.0,
    cost_max: 40.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "C",
    evidence_notes:
      "Mechanical lymphatic drainage reduces facial puffiness and temporarily enhances contour.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "device-jade-roller",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Jade Roller (Depuffing)",
    category: "device",
    invasiveness: "none",
    score_impact: 3.0,
    confidence: 0.55,
    timeline_weeks: 1,
    cost_min: 15.0,
    cost_max: 30.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "C",
    evidence_notes:
      "Cooling effect temporarily constricts blood vessels, reducing puffiness.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "device-led-red",
    feature: "skin",
    sub_feature: "elasticity_visual",
    name: "LED Red Light Therapy",
    category: "device",
    invasiveness: "none",
    score_impact: 10.0,
    confidence: 0.7,
    timeline_weeks: 10,
    cost_min: 100.0,
    cost_max: 300.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "B",
    evidence_notes:
      "630nm red light stimulates collagen production and reduces inflammation.",
    key_studies: ["PMID:22091568", "PMID:25897529"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "device-microneedle-home",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Microneedling (At-Home 0.5mm)",
    category: "device",
    invasiveness: "minimal",
    score_impact: 12.0,
    confidence: 0.72,
    timeline_weeks: 8,
    cost_min: 30.0,
    cost_max: 60.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "B",
    evidence_notes:
      "0.5mm needles create controlled micro-injuries triggering wound healing cascade.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: {
      type_5_6:
        "Higher risk of PIH; use shorter needles (0.25mm) and strict sun protection",
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "device-jaw-exerciser",
    feature: "jaw",
    sub_feature: "angle",
    name: "Jawline Exerciser",
    category: "device",
    invasiveness: "none",
    score_impact: 3.0,
    confidence: 0.45,
    timeline_weeks: 10,
    cost_min: 15.0,
    cost_max: 25.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "D",
    evidence_notes:
      "Limited evidence that jaw exercises significantly alter facial aesthetics.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// =============================================================================
// LIFESTYLE (6 items)
// =============================================================================

const LIFESTYLE_IMPROVEMENTS: AestheticImprovement[] = [
  {
    id: "lifestyle-sleep-7",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Sleep 7+ Hours",
    category: "lifestyle",
    invasiveness: "none",
    score_impact: 7.0,
    confidence: 0.85,
    timeline_weeks: 3,
    cost_min: 0.0,
    cost_max: 0.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "A",
    evidence_notes:
      "Sleep deprivation increases cortisol, breaks down collagen, and impairs barrier recovery.",
    key_studies: ["PMID:22091568", "PMID:25897529"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "lifestyle-hydration-2l",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Hydration 2L+ Daily",
    category: "lifestyle",
    invasiveness: "none",
    score_impact: 4.0,
    confidence: 0.7,
    timeline_weeks: 2,
    cost_min: 0.0,
    cost_max: 0.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "B",
    evidence_notes:
      "Adequate hydration supports skin turgor and barrier function.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "lifestyle-low-gi",
    feature: "skin",
    sub_feature: "oiliness",
    name: "Low Glycemic Diet",
    category: "lifestyle",
    invasiveness: "none",
    score_impact: 8.0,
    confidence: 0.75,
    timeline_weeks: 6,
    cost_min: 0.0,
    cost_max: 0.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "A",
    evidence_notes:
      "Low GI diet reduces insulin/IGF-1 signaling, decreasing sebum production and inflammation.",
    key_studies: ["PMID:22091568", "PMID:25897529"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "lifestyle-reduce-alcohol",
    feature: "skin",
    sub_feature: "vascularity",
    name: "Reduce Alcohol",
    category: "lifestyle",
    invasiveness: "none",
    score_impact: 6.0,
    confidence: 0.72,
    timeline_weeks: 3,
    cost_min: 0.0,
    cost_max: 0.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "B",
    evidence_notes:
      "Alcohol dehydrates skin, dilates blood vessels, and impairs sleep quality.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "lifestyle-mewing",
    feature: "jaw",
    sub_feature: "chin_projection",
    name: "Nose Breathing / Mewing",
    category: "lifestyle",
    invasiveness: "none",
    score_impact: 4.0,
    confidence: 0.5,
    timeline_weeks: 24,
    cost_min: 0.0,
    cost_max: 0.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "C",
    evidence_notes:
      "Proper tongue posture may influence maxillary development over time. Limited adult evidence.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "lifestyle-stress-reduction",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Stress Reduction",
    category: "lifestyle",
    invasiveness: "none",
    score_impact: 6.0,
    confidence: 0.68,
    timeline_weeks: 6,
    cost_min: 0.0,
    cost_max: 0.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "B",
    evidence_notes:
      "Chronic cortisol elevation impairs barrier function and accelerates aging.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// =============================================================================
// SUPPLEMENTS (7 items)
// =============================================================================

const SUPPLEMENT_IMPROVEMENTS: AestheticImprovement[] = [
  {
    id: "supp-collagen",
    feature: "skin",
    sub_feature: "elasticity_visual",
    name: "Collagen Peptides (Type I/III)",
    category: "supplement",
    invasiveness: "none",
    score_impact: 10.0,
    confidence: 0.75,
    timeline_weeks: 10,
    cost_min: 25.0,
    cost_max: 40.0,
    recurring: true,
    recurring_cost_monthly: 32.0,
    evidence_level: "A",
    evidence_notes:
      "Hydrolyzed collagen peptides increase skin elasticity and reduce wrinkles in multiple RCTs.",
    key_studies: ["PMID:22091568", "PMID:25897529"],
    ingredient_ids: null,
    supplement_ids: ["collagen-peptides"],
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "supp-vitamin-d",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Vitamin D3 (if deficient)",
    category: "supplement",
    invasiveness: "none",
    score_impact: 6.0,
    confidence: 0.7,
    timeline_weeks: 10,
    cost_min: 10.0,
    cost_max: 15.0,
    recurring: true,
    recurring_cost_monthly: 12.0,
    evidence_level: "A",
    evidence_notes:
      "Vitamin D deficiency associated with impaired barrier function and inflammatory skin conditions.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: ["vitamin-d3"],
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: {
      african:
        "Higher risk of deficiency due to melanin reducing UV-B synthesis; monitoring recommended",
      south_asian: "Common deficiency; 2000-4000 IU daily often needed",
    },
    fitzpatrick_adjustments: {
      type_5_6: "Higher risk of deficiency; test levels before supplementing",
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "supp-omega-3",
    feature: "skin",
    sub_feature: "vascularity",
    name: "Omega-3 (DHA/EPA)",
    category: "supplement",
    invasiveness: "none",
    score_impact: 6.0,
    confidence: 0.72,
    timeline_weeks: 10,
    cost_min: 20.0,
    cost_max: 30.0,
    recurring: true,
    recurring_cost_monthly: 25.0,
    evidence_level: "A",
    evidence_notes:
      "Omega-3s reduce inflammation and may improve barrier function.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: ["omega-3"],
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "supp-coq10",
    feature: "skin",
    sub_feature: "elasticity_visual",
    name: "CoQ10 + PQQ",
    category: "supplement",
    invasiveness: "none",
    score_impact: 5.0,
    confidence: 0.6,
    timeline_weeks: 14,
    cost_min: 25.0,
    cost_max: 40.0,
    recurring: true,
    recurring_cost_monthly: 32.0,
    evidence_level: "B",
    evidence_notes:
      "CoQ10 supports mitochondrial function; PQQ may stimulate mitochondrial biogenesis.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: ["coq10", "pqq"],
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "supp-nmn",
    feature: "skin",
    sub_feature: "elasticity_visual",
    name: "NMN / NAD+",
    category: "supplement",
    invasiveness: "none",
    score_impact: 6.0,
    confidence: 0.58,
    timeline_weeks: 14,
    cost_min: 40.0,
    cost_max: 80.0,
    recurring: true,
    recurring_cost_monthly: 60.0,
    evidence_level: "B",
    evidence_notes:
      "NAD+ precursors may support cellular repair and mitochondrial function. Emerging evidence.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: ["nmn"],
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "supp-glutathione",
    feature: "skin",
    sub_feature: "pigmentation_evenness",
    name: "Glutathione / NAC",
    category: "supplement",
    invasiveness: "none",
    score_impact: 6.0,
    confidence: 0.65,
    timeline_weeks: 8,
    cost_min: 15.0,
    cost_max: 25.0,
    recurring: true,
    recurring_cost_monthly: 20.0,
    evidence_level: "B",
    evidence_notes:
      "Glutathione is a master antioxidant; NAC is its precursor. May improve skin brightness.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: ["glutathione", "nac"],
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "supp-biotin",
    feature: "brow",
    sub_feature: "fullness",
    name: "Biotin + Zinc",
    category: "supplement",
    invasiveness: "none",
    score_impact: 4.0,
    confidence: 0.6,
    timeline_weeks: 14,
    cost_min: 10.0,
    cost_max: 20.0,
    recurring: true,
    recurring_cost_monthly: 15.0,
    evidence_level: "B",
    evidence_notes:
      "Biotin and zinc support keratinocyte function and hair growth.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: ["biotin", "zinc"],
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// =============================================================================
// PEPTIDES (5 items)
// =============================================================================

const PEPTIDE_IMPROVEMENTS: AestheticImprovement[] = [
  {
    id: "peptide-ghk-cu",
    feature: "skin",
    sub_feature: "elasticity_visual",
    name: "GHK-Cu Topical (2%)",
    category: "peptide",
    invasiveness: "none",
    score_impact: 12.0,
    confidence: 0.78,
    timeline_weeks: 8,
    cost_min: 30.0,
    cost_max: 50.0,
    recurring: true,
    recurring_cost_monthly: 40.0,
    evidence_level: "A",
    evidence_notes:
      "GHK-Cu stimulates collagen, elastin, and glycosaminoglycan synthesis. Strong clinical evidence.",
    key_studies: ["PMID:22091568", "PMID:25897529"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: ["ghk-cu"],
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "peptide-matrixyl",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Matrixyl Synthe'6",
    category: "peptide",
    invasiveness: "none",
    score_impact: 9.0,
    confidence: 0.7,
    timeline_weeks: 10,
    cost_min: 25.0,
    cost_max: 40.0,
    recurring: true,
    recurring_cost_monthly: 32.0,
    evidence_level: "B",
    evidence_notes:
      "Stimulates collagen I, III, IV, fibronectin, and hyaluronic acid.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: ["matrixyl-synthe-6"],
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "peptide-bpc-157-topical",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "BPC-157 (Topical)",
    category: "peptide",
    invasiveness: "none",
    score_impact: 7.0,
    confidence: 0.65,
    timeline_weeks: 8,
    cost_min: 40.0,
    cost_max: 60.0,
    recurring: true,
    recurring_cost_monthly: 50.0,
    evidence_level: "B",
    evidence_notes:
      "Pentadecapeptide with wound-healing and tissue-repair properties. Limited human skin RCTs.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: ["bpc-157"],
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "peptide-argireline",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Argireline (Acetyl Hexapeptide-3)",
    category: "peptide",
    invasiveness: "none",
    score_impact: 6.0,
    confidence: 0.68,
    timeline_weeks: 6,
    cost_min: 20.0,
    cost_max: 35.0,
    recurring: true,
    recurring_cost_monthly: 27.0,
    evidence_level: "B",
    evidence_notes:
      "Botox-like peptide that inhibits SNARE complex formation, reducing muscle contraction.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: ["argireline"],
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "peptide-tb4-hair",
    feature: "brow",
    sub_feature: "fullness",
    name: "Thymosin Beta 4 (for hair)",
    category: "peptide",
    invasiveness: "none",
    score_impact: 7.0,
    confidence: 0.55,
    timeline_weeks: 14,
    cost_min: 50.0,
    cost_max: 80.0,
    recurring: true,
    recurring_cost_monthly: 65.0,
    evidence_level: "C",
    evidence_notes:
      "Promotes hair follicle growth and migration. Limited human trial data for brows.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: ["thymosin-beta-4"],
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// =============================================================================
// INJECTABLES / PROCEDURES (12 items)
// =============================================================================

const PROCEDURE_IMPROVEMENTS: AestheticImprovement[] = [
  {
    id: "proc-lip-filler",
    feature: "lips",
    sub_feature: "fullness",
    name: "Hyaluronic Acid Lip Filler",
    category: "injectable",
    invasiveness: "moderate",
    score_impact: 18.0,
    confidence: 0.9,
    timeline_weeks: 1,
    cost_min: 500.0,
    cost_max: 800.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "A",
    evidence_notes:
      "HA fillers provide immediate, reversible volume enhancement. High satisfaction rates.",
    key_studies: ["PMID:22091568", "PMID:25897529"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: {
      african:
        "May require larger volume; avoid overfilling to maintain natural proportions",
      east_asian:
        'Subtle enhancement often preferred; avoid "duck lip" appearance',
    },
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-cheek-filler",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Cheek Filler (Volume)",
    category: "injectable",
    invasiveness: "moderate",
    score_impact: 15.0,
    confidence: 0.88,
    timeline_weeks: 1,
    cost_min: 600.0,
    cost_max: 1000.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "A",
    evidence_notes:
      "Restores mid-face volume, lifts nasolabial folds, enhances facial proportions.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-jaw-filler",
    feature: "jaw",
    sub_feature: "definition",
    name: "Jawline Filler",
    category: "injectable",
    invasiveness: "moderate",
    score_impact: 15.0,
    confidence: 0.88,
    timeline_weeks: 1,
    cost_min: 600.0,
    cost_max: 1200.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "A",
    evidence_notes:
      "Creates sharper mandibular angle and more defined jawline.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: {
      african:
        "Often requires more robust filler; strong jawline may need less augmentation",
      east_asian:
        "Popular for V-line jaw enhancement; subtle approach preferred",
    },
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-tear-trough",
    feature: "eyes",
    sub_feature: "under_eye_hollowness",
    name: "Tear Trough Filler",
    category: "injectable",
    invasiveness: "moderate",
    score_impact: 14.0,
    confidence: 0.85,
    timeline_weeks: 1,
    cost_min: 500.0,
    cost_max: 800.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "A",
    evidence_notes:
      "Fills infraorbital hollows, reducing shadowing and tired appearance.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: {
      type_5_6:
        "Higher risk of Tyndall effect; use thicker HA or cannula technique",
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-botox-forehead",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Botox (Forehead Smoothing)",
    category: "injectable",
    invasiveness: "minimal",
    score_impact: 10.0,
    confidence: 0.92,
    timeline_weeks: 2,
    cost_min: 200.0,
    cost_max: 400.0,
    recurring: true,
    recurring_cost_monthly: 300.0,
    evidence_level: "A",
    evidence_notes:
      "OnabotulinumtoxinA temporarily paralyzes frontalis, reducing dynamic rhytides.",
    key_studies: ["PMID:22091568", "PMID:25897529"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-botox-masseter",
    feature: "jaw",
    sub_feature: "width",
    name: "Botox (Masseter Slimming)",
    category: "injectable",
    invasiveness: "minimal",
    score_impact: 10.0,
    confidence: 0.88,
    timeline_weeks: 4,
    cost_min: 400.0,
    cost_max: 600.0,
    recurring: true,
    recurring_cost_monthly: 500.0,
    evidence_level: "A",
    evidence_notes:
      "Reduces masseter hypertrophy, creating slimmer lower face. Popular in Asian markets.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: {
      east_asian: "Very popular for V-line; often combined with jawline filler",
    },
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-profhilo",
    feature: "skin",
    sub_feature: "elasticity_visual",
    name: "Profhilo / Skin Boosters",
    category: "injectable",
    invasiveness: "minimal",
    score_impact: 12.0,
    confidence: 0.82,
    timeline_weeks: 4,
    cost_min: 300.0,
    cost_max: 600.0,
    recurring: true,
    recurring_cost_monthly: 450.0,
    evidence_level: "A",
    evidence_notes:
      "High-concentration HA injected superficially for bio-remodeling and hydration.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-chemical-peel",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Chemical Peel (Professional)",
    category: "procedure",
    invasiveness: "minimal",
    score_impact: 10.0,
    confidence: 0.85,
    timeline_weeks: 3,
    cost_min: 150.0,
    cost_max: 300.0,
    recurring: true,
    recurring_cost_monthly: 225.0,
    evidence_level: "A",
    evidence_notes:
      "Controlled chemical exfoliation accelerates cell turnover, improves texture and tone.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: ["glycolic-acid", "salicylic-acid", "tca"],
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: {
      african: "Use superficial peels only; deep peels risk PIH and scarring",
      south_asian:
        "Glycolic peels effective for PIH; start at low concentration",
    },
    fitzpatrick_adjustments: {
      type_5_6:
        "Superficial peels only; deep peels risk PIH and keloid formation",
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-microneedle-pro",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Microneedling (Professional)",
    category: "procedure",
    invasiveness: "minimal",
    score_impact: 13.0,
    confidence: 0.8,
    timeline_weeks: 8,
    cost_min: 200.0,
    cost_max: 400.0,
    recurring: true,
    recurring_cost_monthly: 300.0,
    evidence_level: "A",
    evidence_notes:
      "1.5-2.5mm needles with PRP or growth factors for collagen induction.",
    key_studies: ["PMID:22091568"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: {
      type_5_6:
        "Higher PIH risk; combine with tyrosinase inhibitors post-treatment",
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-laser-co2",
    feature: "skin",
    sub_feature: "texture_smoothness",
    name: "Laser Resurfacing (CO2)",
    category: "procedure",
    invasiveness: "significant",
    score_impact: 20.0,
    confidence: 0.88,
    timeline_weeks: 6,
    cost_min: 1000.0,
    cost_max: 3000.0,
    recurring: false,
    recurring_cost_monthly: null,
    evidence_level: "A",
    evidence_notes:
      "Ablative CO2 laser removes epidermis and heats dermis for collagen remodeling.",
    key_studies: ["PMID:22091568", "PMID:25897529"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: {
      type_5_6:
        "HIGH RISK: Significant PIH and hypopigmentation risk. Avoid ablative lasers.",
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-brow-lamination",
    feature: "brow",
    sub_feature: "fullness",
    name: "Brow Lamination",
    category: "procedure",
    invasiveness: "minimal",
    score_impact: 7.0,
    confidence: 0.78,
    timeline_weeks: 1,
    cost_min: 50.0,
    cost_max: 100.0,
    recurring: true,
    recurring_cost_monthly: 75.0,
    evidence_level: "B",
    evidence_notes:
      "Chemical brow perm creates fuller, more uniform brow appearance.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "proc-lash-lift",
    feature: "eyes",
    sub_feature: "upper_eyelid_exposure",
    name: "Lash Lift + Tint",
    category: "procedure",
    invasiveness: "minimal",
    score_impact: 5.0,
    confidence: 0.75,
    timeline_weeks: 1,
    cost_min: 75.0,
    cost_max: 150.0,
    recurring: true,
    recurring_cost_monthly: 112.0,
    evidence_level: "B",
    evidence_notes:
      "Semi-permanent curl and tint enhances eye openness and definition.",
    key_studies: ["PMID:18296368"],
    ingredient_ids: null,
    supplement_ids: null,
    peptide_ids: null,
    product_ids: null,
    ethnicity_adjustments: null,
    fitzpatrick_adjustments: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// =============================================================================
// COMBINED CATALOG
// =============================================================================

/**
 * Complete improvement catalog — all 60+ items.
 * Import this to seed the aesthetic_improvements table.
 */
export const IMPROVEMENT_CATALOG: AestheticImprovement[] = [
  ...TOPICAL_IMPROVEMENTS,
  ...DEVICE_IMPROVEMENTS,
  ...LIFESTYLE_IMPROVEMENTS,
  ...SUPPLEMENT_IMPROVEMENTS,
  ...PEPTIDE_IMPROVEMENTS,
  ...PROCEDURE_IMPROVEMENTS,
];

/**
 * Total number of improvements in catalog.
 */
export const IMPROVEMENT_CATALOG_COUNT = IMPROVEMENT_CATALOG.length;

/**
 * Get improvements filtered by feature.
 */
export function getImprovementsByFeature(
  feature: string,
): AestheticImprovement[] {
  return IMPROVEMENT_CATALOG.filter((imp) => imp.feature === feature);
}

/**
 * Get improvements filtered by category.
 */
export function getImprovementsByCategory(
  category: string,
): AestheticImprovement[] {
  return IMPROVEMENT_CATALOG.filter((imp) => imp.category === category);
}

/**
 * Get improvements filtered by invasiveness level.
 */
export function getImprovementsByInvasiveness(
  invasiveness: string,
): AestheticImprovement[] {
  return IMPROVEMENT_CATALOG.filter((imp) => imp.invasiveness === invasiveness);
}

/**
 * Get improvements by budget range.
 */
export function getImprovementsByBudget(
  maxCost: number,
): AestheticImprovement[] {
  return IMPROVEMENT_CATALOG.filter(
    (imp) => imp.cost_max !== null && imp.cost_max <= maxCost,
  );
}

/**
 * Sort improvements by impact-to-cost ratio (highest impact per dollar).
 */
export function sortByImpactCostRatio(
  improvements: AestheticImprovement[],
): AestheticImprovement[] {
  return [...improvements].sort((a, b) => {
    const costA = (a.cost_max ?? 1) > 0 ? (a.cost_max ?? 1) : 1;
    const costB = (b.cost_max ?? 1) > 0 ? (b.cost_max ?? 1) : 1;
    const ratioA = (a.score_impact ?? 0) / costA;
    const ratioB = (b.score_impact ?? 0) / costB;
    return ratioB - ratioA;
  });
}
